libandroid/lib/gradle.properties, libjava/lib/gradle.properties
=> Bump SNAPSHOT to 1.1.0

libandroid/build.gradle, libjava/build.gradle, libjava/lib/src/main/java/com/mapbox/services/directions/v4/MapboxDirections.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/MapboxDirections.java, libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/MapboxGeocoding.java, libjava/lib/src/main/java/com/mapbox/services/staticimage/v1/MapboxStaticImage.java, libjava/lib/src/test/java/com/mapbox/services/directions/v5/MapboxDirectionsTest.java
=> Force Locale.US in all String.Format

libandroid/lib/proguard-rules.pro
Fixes #28.
/cc: @cammace @bleege
=> Add proguard rules to android library

libjava/lib/build.gradle, libjava/lib/src/main/java/com/mapbox/services/commons/utils/MapboxUtils.java, libjava/lib/src/main/java/com/mapbox/services/commons/utils/TextUtils.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/MapboxDirections.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/MapboxDirections.java
Reduces the number of methods brought by external dependencies.
/cc: @cammace
=> Replaces org.apache.commons:commons-lang3 with TextUtils subset

libandroid/app/build.gradle, libandroid/lib/build.gradle, libjava/app/build.gradle
=> Upgrade support and tools numbers

libandroid/app/src/main/java/com/mapbox/services/android/testapp/MainActivity.java, libandroid/lib/build.gradle, libandroid/lib/gradle.properties
=> Add versionCode and versionName values

libjava/lib/src/main/java/com/mapbox/services/directions/v4/MapboxDirections.java, libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/MapboxGeocoding.java, libjava/lib/src/test/java/com/mapbox/services/geocoding/v5/MapboxGeocodingTest.java
=> Geocoding Observerable NullPointerException Fix

libandroid/CHANGELOG.md, libandroid/app/src/main/AndroidManifest.xml, libandroid/app/src/main/java/com/mapbox/services/android/testapp/MainActivity.java, libandroid/app/src/main/java/com/mapbox/services/android/testapp/staticimage/StaticImageActivity.java, libandroid/lib/build.gradle, libandroid/lib/gradle.properties, libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/ui/GeocoderAdapter.java, libjava/CHANGELOG.md, libjava/lib/gradle.properties, libjava/lib/src/main/java/com/mapbox/services/commons/geojson/custom/GeometryDeserializer.java
Related ticket #55.
/cc: @cammace
=> Release v1.1.0

libjava/lib/src/main/java/com/mapbox/services/commons/utils/PolylineUtils.java, libjava/lib/src/test/java/com/mapbox/services/utils/PolylineUtilsTest.java
Direct port of the [`simplify-js`](https://github.com/mourner/simplify-js) code (including tests) to Java.
/cc: @ivovandongen @mourner @cammace
=> Brings simplify-js to Mapbox Android Services

libjava/lib/src/main/java/com/mapbox/services/Constants.java, libjava/lib/src/test/java/com/mapbox/services/staticimage/v1/MapboxStaticImageTest.java
=> Updating Styles to V9; Deprecating Emerald

libjava/lib/build.gradle, libjava/lib/src/main/java/com/mapbox/services/commons/MapboxService.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/MapboxDirections.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/MapboxDirections.java, libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/MapboxGeocoding.java, libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/MapMatchingService.java, libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/MapboxMapMatching.java, libjava/lib/src/test/java/com/mapbox/services/geojson/LineStringTest.java, libjava/lib/src/test/java/com/mapbox/services/mapmatching/v4/MapboxMapMatchingTest.java
See the original implementation: https://github.com/mapbox/mapbox-java/pull/64.
This fixes it, and bring updated libraries and better logging.
/cc: @cammace
=> Map Matching: body of the request was missing

libjava/lib/src/main/java/com/mapbox/services/Constants.java, libjava/lib/src/main/java/com/mapbox/services/commons/MapboxService.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/DirectionsService.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/MapboxDirections.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/DirectionsService.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/MapboxDirections.java, libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/GeocodingService.java, libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/MapboxGeocoding.java, libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/MapMatchingService.java, libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/MapboxMapMatching.java, libjava/lib/src/test/java/com/mapbox/services/ConstantsTest.java
For now I'm setting: `MapboxAndroidServices/1.0`.
@1ec5 : Do you know if there is a better rule for this?
Fixes #74.
/cc: @cammace
=> Customize user agent string

libandroid/app/src/main/java/com/mapbox/services/android/testapp/directions/DirectionsV5Activity.java, libandroid/lib/build.gradle
also added full overview to directions activity so the route is drawn accurately. This should fix bitrise error and allow us to build new snapshot!
cc: @zugaldia
=> bumped to 1.2.0 snapshot

libandroid/app/src/main/java/com/mapbox/services/android/testapp/geocoding/GeocodingReverseActivity.java, libandroid/app/src/main/java/com/mapbox/services/android/testapp/geocoding/GeocodingWidgetActivity.java, libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/AndroidGeocoder.java, libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/GeocoderUtils.java, libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/ui/GeocoderAdapter.java, libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/ui/GeocoderAutoCompleteView.java
This PR resolves issues in libandroid since updates were made in libjava. 
cc: @zugaldia
=> Fix geocoder issues in libandroid

libandroid/app/src/main/java/com/mapbox/services/android/testapp/staticimage/StaticImageActivity.java
=> Replaced emerald for outdoor style in static image

libandroid/CHANGELOG.md, libandroid/app/src/main/java/com/mapbox/services/android/testapp/staticimage/StaticImageActivity.java, libandroid/app/src/main/java/com/mapbox/services/android/testapp/utils/MapMatchingActivity.java, libandroid/app/src/main/java/com/mapbox/services/android/testapp/utils/SimplifyPolylineActivity.java, libandroid/lib/build.gradle, libandroid/lib/gradle.properties, libjava/CHANGELOG.md, libjava/lib/gradle.properties, libjava/lib/src/main/java/com/mapbox/services/Constants.java, libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/gson/MapMatchingGeometryDeserializer.java
See https://github.com/mapbox/mapbox-java/issues/107.
=> Release 1.2.0

libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/models/CarmenFeature.java
Fixes https://github.com/mapbox/mapbox-java/issues/109.
/cc: @cammace
=> Bring back toString method in CarmenFeature

libandroid/lib/build.gradle, libandroid/settings.gradle
Helps with https://github.com/mapbox/mapbox-java/issues/95.
/cc: @cammace
=> Use master branch from libjava during dev

libandroid/CHANGELOG.md, libandroid/lib/build.gradle, libjava/CHANGELOG.md
=> Release 1.2.1

README.md
Updated the badge count, total methods: 30186 -> to 30733. Also added information about the demo application in play store.
=> Updated badge count

checkstyle.xml, libandroid/lib/build.gradle, libandroid/lib/gradle-checkstyle.gradle, libjava/lib/build.gradle, libjava/lib/gradle-checkstyle.gradle
Fixes https://github.com/mapbox/mapbox-java/issues/111.
/cc: @cammace
=> Add checkstyle.xml and gradle settings

libandroid/app/src/main/AndroidManifest.xml, libandroid/app/src/main/java/com/mapbox/services/android/testapp/MainActivity.java, libandroid/app/src/main/java/com/mapbox/services/android/testapp/turf/TurfLineSliceActivity.java, libandroid/app/src/main/res/layout/activity_turf_line_slice.xml, libandroid/app/src/main/res/layout/content_turf_line_slice.xml
=> Line slice example added

libandroid/app/src/main/java/com/mapbox/services/android/testapp/utils/SimplifyPolylineActivity.java, libandroid/app/src/main/res/layout/activity_utils_simplify_polyline.xml, libjava/lib/src/main/java/com/mapbox/services/commons/utils/PolylineUtils.java
For consistency with http://mourner.github.io/simplify-js/ I'm bringing the default tolerance value to 1 and adjusting the test activity accordingly.
/cc: @cammace
=> Bring default tolerance value to 1

libandroid/app/src/main/AndroidManifest.xml, libandroid/app/src/main/java/com/mapbox/services/android/testapp/MasApplication.java, libandroid/app/src/main/java/com/mapbox/services/android/testapp/directions/DirectionsV4Activity.java, libandroid/app/src/main/java/com/mapbox/services/android/testapp/directions/DirectionsV5Activity.java, libandroid/app/src/main/java/com/mapbox/services/android/testapp/geocoding/GeocodingReverseActivity.java, libandroid/app/src/main/java/com/mapbox/services/android/testapp/geocoding/GeocodingWidgetActivity.java, libandroid/app/src/main/java/com/mapbox/services/android/testapp/turf/TurfBearingActivity.java, libandroid/app/src/main/java/com/mapbox/services/android/testapp/turf/TurfDestinationActivity.java, libandroid/app/src/main/java/com/mapbox/services/android/testapp/turf/TurfDistanceActivity.java, libandroid/app/src/main/java/com/mapbox/services/android/testapp/turf/TurfLineSliceActivity.java, libandroid/app/src/main/java/com/mapbox/services/android/testapp/utils/MapMatchingActivity.java, libandroid/app/src/main/java/com/mapbox/services/android/testapp/utils/SimplifyPolylineActivity.java
Added application object and removed all mapview set access token usages.
cc: @zugaldia
=> Test app using account manager

libjava/lib/src/main/java/com/mapbox/services/commons/models/Position.java
=> Override toString method in position

libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/ui/GeocoderAdapter.java, libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/ui/GeocoderAutoCompleteView.java, libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/MapboxGeocoding.java
Closes #130. I've added `setbbox()` to the geocoding widget. 
cc: @zugaldia
=> Geocoding autocomplete widget bbox

CONTRIBUTING.md, INSTALL.md
=> added install and contributing markdown files

libjava/lib/src/main/java/com/mapbox/services/commons/models/Position.java, libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfConstants.java, libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfException.java, libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfGrids.java, libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfHelpers.java, libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfInvariant.java, libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfJoins.java, libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfMeasurement.java, libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfMisc.java, libjava/lib/src/main/java/com/mapbox/services/commons/turf/models/LineIntersectsResult.java
All Turf methods now have appropriate javadoc. Going ahead and merging!
cc: @zugaldia
=> Added missing Turf javadoc

libjava/lib/src/main/java/com/mapbox/services/commons/MapboxBuilder.java, libjava/lib/src/main/java/com/mapbox/services/commons/MapboxService.java, libjava/lib/src/main/java/com/mapbox/services/commons/ServicesException.java, libjava/lib/src/main/java/com/mapbox/services/commons/utils/MapboxUtils.java, libjava/lib/src/main/java/com/mapbox/services/commons/utils/PolylineUtils.java, libjava/lib/src/main/java/com/mapbox/services/commons/utils/TextUtils.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/DirectionsCriteria.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/DirectionsService.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/MapboxDirections.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/DirectionsFeature.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/DirectionsResponse.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/DirectionsRoute.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/FeatureGeometry.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/FeatureProperties.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/ManeuverPoint.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/RouteStep.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/StepManeuver.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/Waypoint.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/DirectionsCriteria.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/DirectionsService.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/MapboxDirections.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/models/DirectionsResponse.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/models/DirectionsRoute.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/models/DirectionsWaypoint.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/models/LegStep.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/models/RouteLeg.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/models/StepManeuver.java
So far, with this PR along with #139 the amount of errors and warning have changed from:
errors: 100 -> 5
warnings: 50 -> 100
cc: @zugaldia
=> Directions javadoc fixes

libandroid/app/build.gradle
Updated some of the dependencies in the test app include Mapbox Android to `4.1.1`. Tested and all activities worked fine.
=> Updated testapp dependencies

libjava/lib/src/main/java/com/mapbox/services/commons/geojson/Feature.java, libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/models/CarmenFeature.java, libjava/lib/src/test/java/com/mapbox/services/geocoding/v5/CarmenFeatureTest.java
Fixes #148.
@cammace Feel free to merge if this is what you're looking for.
=> Enable CarmenFeature to be used as a standalone object

libandroid/app/src/main/AndroidManifest.xml, libandroid/lib/build.gradle, libandroid/lib/gradle-javadoc.gradle
Instead of from FS.
Fixes https://github.com/mapbox/mapbox-java/issues/154.
/cc: @cammace
=> Make snapshots build from mapbox-java-services:2.0.0-SNAPSHOT@jar

libandroid/app/src/main/java/com/mapbox/services/android/testapp/directions/DirectionsV5Activity.java, libjava/lib/build.gradle, libjava/lib/src/main/java/com/mapbox/services/commons/MapboxService.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/DirectionsService.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/MapboxDirections.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/DirectionsService.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/MapboxDirections.java, libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/GeocodingService.java, libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/MapboxGeocoding.java, libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/MapMatchingService.java, libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/MapboxMapMatching.java, libjava/lib/src/test/java/com/mapbox/services/geocoding/v5/MapboxGeocodingTest.java, libjava/lib/src/test/java/com/mapbox/services/mapmatching/v4/MapboxMapMatchingTest.java
The plan is to extract this functionality as an optional module for devs.
Fixes #131.
/cc: @ivovandongen
=> Remove RxJava dependencies

README.md
=> Be explicit about features in the README

libjava/lib/src/main/java/com/mapbox/services/commons/geojson/GeometryCollection.java, libjava/lib/src/main/java/com/mapbox/services/commons/geojson/LineString.java, libjava/lib/src/main/java/com/mapbox/services/commons/geojson/MultiLineString.java, libjava/lib/src/main/java/com/mapbox/services/commons/geojson/MultiPoint.java, libjava/lib/src/main/java/com/mapbox/services/commons/geojson/MultiPolygon.java, libjava/lib/src/main/java/com/mapbox/services/commons/geojson/Point.java, libjava/lib/src/main/java/com/mapbox/services/commons/geojson/Polygon.java, libjava/lib/src/main/java/com/mapbox/services/commons/models/Position.java
Fixes https://github.com/mapbox/mapbox-java/issues/171
@ivovandongen Is it something like this that you had in mind? The conversions feel hacky for some reason, I want to see if there's a better way to accomplish this.
Either way, before merging, this needs:
=> Add support for primitive arrays

libjava/lib/src/main/java/com/mapbox/services/directions/v5/models/DirectionsResponse.java, libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/models/GeocodingResponse.java, libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/models/MapMatchingResponse.java
Fixes https://github.com/mapbox/mapbox-java/issues/174.
/cc: @cammace
=> Make response constructors public for testing

README.md
Fixes `libandroid` features in readme pointed out by @zugaldia in #169.
=> reworded libandroid features in readme

README.md
=> Updated method count badge for 1.3

README.md, libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/ui/GeocoderAdapter.java, libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/ui/GeocoderAutoCompleteView.java, libjava/lib/src/main/java/com/mapbox/services/commons/geojson/Feature.java, libjava/lib/src/main/java/com/mapbox/services/commons/models/Position.java, libjava/lib/src/main/java/com/mapbox/services/commons/tidy/Tidy.java, libjava/lib/src/main/java/com/mapbox/services/commons/tidy/package-info.java, libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfGrids.java, libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfJoins.java, libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfMeasurement.java, libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfMisc.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/models/LegStep.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/models/StepIntersection.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/models/StepManeuver.java, libjava/lib/src/main/java/com/mapbox/services/navigation/v5/RouteUtils.java, libjava/lib/src/main/java/com/mapbox/services/navigation/v5/package-info.java
Adds javadoc to `RouteUtils` class and changes `@since` tags from 2.0.0 to 1.3.0. Before merging I need more info on the tidy class @zugaldia.
=> Updated javadoc in code for 1.3.0

api/libandroid/index.md, api/libjava/index.md
Forgot to change the redirect link in index files...
=> Updated redirect link in index files

libjava/lib/src/main/java/com/mapbox/services/commons/geojson/MultiLineString.java, libjava/lib/src/main/java/com/mapbox/services/commons/models/Position.java, libjava/lib/src/test/java/com/mapbox/services/geojson/LineStringTest.java, libjava/lib/src/test/java/com/mapbox/services/geojson/MultiLineStringTest.java, libjava/lib/src/test/java/com/mapbox/services/geojson/MultiPointTest.java, libjava/lib/src/test/java/com/mapbox/services/geojson/MultiPolygonTest.java, libjava/lib/src/test/java/com/mapbox/services/geojson/PointTest.java, libjava/lib/src/test/java/com/mapbox/services/geojson/PolygonTest.java, libjava/lib/src/test/java/com/mapbox/services/models/PositionTest.java
=> Geojson raw array tests

libandroid/CHANGELOG.md, libjava/CHANGELOG.md
See https://github.com/mapbox/mapbox-java/issues/198.
/cc: @cammace for review.
=> Added changelog

README.md
I've switched to using mapbox-java instead to better represent this library.
cc: @zugaldia
=> updated method count badge

libjava/.gitignore, libjava/lib/build-config.gradle, libjava/lib/build.gradle, libjava/lib/src/main/java/com/mapbox/services/Constants.java, libjava/lib/src/main/java/com/mapbox/services/commons/MapboxBuilder.java, libjava/lib/src/main/java/com/mapbox/services/commons/MapboxService.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/MapboxDirections.java, libjava/lib/src/main/java/com/mapbox/services/directions/v5/MapboxDirections.java, libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/MapboxGeocoding.java, libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/MapboxMapMatching.java, libjava/lib/src/main/java/com/mapbox/services/staticimage/v1/MapboxStaticImage.java, libjava/lib/src/test/java/com/mapbox/services/ConstantsTest.java, libjava/lib/src/test/java/com/mapbox/services/directions/v5/MapboxDirectionsTest.java, libjava/lib/src/test/java/com/mapbox/services/geocoding/v5/MapboxGeocodingTest.java, libjava/lib/src/test/java/com/mapbox/services/mapmatching/v4/MapboxMapMatchingTest.java
=> Improve User-Agent string

libjava/CHANGELOG.md, libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/GeocodingCriteria.java, libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/MapboxGeocoding.java
dropped in `poi.landmark`. Hoping to see what CI tests say, then take it from there. Eyes appreciated, I'm totally unfamiliar with Java development.
=> add poi.landmark type to geocoder

libandroid/app/build.gradle, libandroid/app/src/main/java/com/mapbox/services/android/testapp/MasApplication.java
Closes #225 
@tobrun can you review this one?
=> Added leak canary to testapp

.gitignore, libandroid/.gitignore, libandroid/app/build.gradle, libandroid/app/gradle-checkstyle.gradle, libandroid/app/gradle-config.gradle, libandroid/lib/build.gradle, libandroid/lib/gradle-checkstyle.gradle, libjava/.gitignore, libjava/build.gradle, libjava/lib/build.gradle, libjava/lib/gradle-checkstyle.gradle, scripts/bitrise.yml
Closes: #220
Closes: #111
cc: @tobrun
=> fixed checkstyle, fixed gitignore, and added config.gradle

Makefile, libandroid/lib/build.gradle, libandroid/lib/gradle-javadoc.gradle, libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/AndroidGeocoder.java, libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/ui/GeocoderAdapter.java, libandroid/lib/src/main/java/com/mapbox/services/android/utils/PermissionsUtils.java, libandroid/lib/src/main/java/overview.html, libjava/lib/build.gradle, libjava/lib/gradle-javadoc.gradle, libjava/lib/src/main/java/com/mapbox/services/distance/v1/gson/package-info.java, libjava/lib/src/main/java/com/mapbox/services/distance/v1/models/package-info.java, libjava/lib/src/main/java/com/mapbox/services/distance/v1/package-info.java, libjava/lib/src/main/java/overview.html
Closes #121 
@tobrun for review
=> fixed javadoc errors

libandroid/app/src/main/java/com/mapbox/services/android/testapp/utils/MapMatchingActivity.java, libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/MapMatchingCriteria.java, libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/MapMatchingService.java, libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/MapboxMapMatching.java
Closes https://github.com/mapbox/mapbox-java/issues/163
cc: @ivovandongen or @tobrun for review
=> adds MapMatchingCriteria

libjava/lib/src/main/java/com/mapbox/services/directions/v4/DirectionsCriteria.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/DirectionsService.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/MapboxDirections.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/DirectionsFeature.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/DirectionsResponse.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/DirectionsRoute.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/FeatureGeometry.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/FeatureProperties.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/ManeuverPoint.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/RouteStep.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/StepManeuver.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/Waypoint.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/models/package-info.java, libjava/lib/src/main/java/com/mapbox/services/directions/v4/package-info.java
Closes: https://github.com/mapbox/mapbox-java/issues/140
Deprecates directions v4 in favor of v5. 
cc: @ivovandongen
=> Deprecated direction v4

libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfHelpers.java
=> fixed meter unit issue

.gitignore
=> Add new gitignore rule to avoid tracking the signing file

mapbox/libjava-services/src/main/java/com/mapbox/services/api/geocoding/v5/models/CarmenFeature.java
Closes https://github.com/mapbox/mapbox-java/issues/242
Rewrote address documentation to make it clear the value can be null
=> Improved address documentation

mapbox/libandroid-ui/src/main/java/com/mapbox/services/android/ui/geocoder/GeocoderAdapter.java, mapbox/libandroid-ui/src/main/java/com/mapbox/services/android/ui/geocoder/GeocoderAutoCompleteView.java
Closes https://github.com/mapbox/mapbox-java/issues/243
=> Removed geocoder lowercase documentation

mapbox/app/src/main/AndroidManifest.xml, mapbox/app/src/main/java/com/mapbox/services/android/testapp/MainActivity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/connectivity/ConnectivityActivity.java, mapbox/app/src/main/res/layout/activity_connectivity.xml, mapbox/app/src/main/res/values/strings.xml, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/connectivity/ConnectivityListener.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/connectivity/ConnectivityReceiver.java
=> add a ConnectivityReceiver/ConnectivityListener pair

mapbox/app/src/main/AndroidManifest.xml, mapbox/app/src/main/java/com/mapbox/services/android/testapp/MainActivity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/nav/SnapToRouteActivity.java, mapbox/app/src/main/res/drawable/ic_expand_less_24dp.xml, mapbox/app/src/main/res/drawable/ic_expand_more_24dp.xml, mapbox/app/src/main/res/layout/activity_snap_to_route.xml, mapbox/app/src/main/res/values/strings.xml
Brings over some of the code from #228
=> adds a snap to route activity to testapp

mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxEvent.java
=> Add gesture keys to the telemetry module

mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/MapboxDirections.java
=> Change coordinates ArrayList to List so users can pass in generic types

mapbox/app/gradle-config.gradle, mapbox/libjava-services/src/main/java/com/mapbox/services/api/staticimage/v1/MapboxStaticImage.java
In order to build the project using IntelliJ IDEA, some issues have to be fixed:
It doesn't affect AS at all.
=> Intellij support

README.md
Fixes https://github.com/mapbox/mapbox-java/issues/306.
@cammace please review.
cc: @tobrun
=> Update README with new modules and contributing information

mapbox/app/src/main/java/com/mapbox/services/android/testapp/geocoding/GeocodingServiceActivity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/geocoding/GeocodingWidgetActivity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/location/GoogleLocationEngine.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/location/LocationEngineActivity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/location/LostLocationEngine.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/location/AndroidLocationEngine.java
Fixes #301 
Added some `WeakReference`'s to avoid unwanted memory leaks.
👀  @zugaldia
=> Fix failing location activities

mapbox/app/src/main/java/com/mapbox/services/android/testapp/utils/MapMatchingActivity.java, mapbox/libjava-core/src/main/java/com/mapbox/services/Constants.java
Fixes https://github.com/mapbox/mapbox-java/issues/311.
=> Introduce PRECISION_5 and PRECISION_6 constants

mapbox/app/src/main/java/com/mapbox/services/android/testapp/nav/OffRouteDetectionActivity.java
=> Fix NPE in OffRouteDetectionActivity

mapbox/libandroid-ui/src/main/java/com/mapbox/services/android/ui/geocoder/GeocoderAdapter.java, mapbox/libandroid-ui/src/main/java/com/mapbox/services/android/ui/geocoder/GeocoderAutoCompleteView.java, mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/geocoding/v5/GeocodingServiceRx.java, mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/geocoding/v5/MapboxGeocodingRx.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/geocoding/v5/GeocodingService.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/geocoding/v5/MapboxGeocoding.java, mapbox/libjava-services/src/test/java/com/mapbox/services/api/geocoding/v5/MapboxGeocodingTest.java
Fixes https://github.com/mapbox/mapbox-java/issues/281.
=> Add optional language parameter to geocoder

mapbox/libjava-services/src/test/java/com/mapbox/services/api/geocoding/v5/CarmenFeatureTest.java
Fixes #280 
- Add toJson test
- Polish tests:
- Use `compareJson` from `BaseTest`
- Develop `CarmenFeatureBuilder` in order to improve _Arrange_ parts
- Improve naming
What do you think @cammace? Is there anything you would like to add?
cc/ @zugaldia
=> Add toJson test and polish previous ones

mapbox/app/build.gradle, mapbox/app/src/main/AndroidManifest.xml, mapbox/app/src/main/java/com/mapbox/services/android/testapp/Utils.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/directions/RouteUtilsV5Activity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/nav/OffRouteDetectionActivity.java, mapbox/libandroid-services/proguard-rules.pro
* Updates Retrofit2 and Gson rules.
* Remove Rx rules and updates MAS rules with new namespaces.
Fixes https://github.com/mapbox/mapbox-java/issues/240.
=> Update proguard rules

mapbox/app/build.gradle, mapbox/app/src/main/java/com/mapbox/services/android/testapp/geocoding/GeocodingWidgetActivity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/location/LocationEngineActivity.java, mapbox/libandroid-services/build.gradle, mapbox/libandroid-services/src/main/java/com/mapbox/services/android/location/LostLocationEngine.java
=> Expose LostLocationEngine in library

CHANGELOG.md, mapbox/gradle.properties
See: https://github.com/mapbox/mapbox-java/issues/322
cc: @cammace
=> Release 2.0.0-beta.1

mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/MapboxDirections.java
https://github.com/mapbox/mapbox-java/issues/321
=> setGeometries now returns an abstract builder type

mapbox/libandroid-ui/src/main/java/com/mapbox/services/android/ui/geocoder/GeocoderAdapter.java, mapbox/libandroid-ui/src/main/java/com/mapbox/services/android/ui/geocoder/GeocoderAutoCompleteView.java
Fixes https://github.com/mapbox/mapbox-java/issues/327.
@cammace please review.
=> Expose base URL param in widget

README.md
Closes: https://github.com/mapbox/mapbox-java/issues/336
=> fixed read me issue

README.md, _config.yml, index.html
Closes #331 
Fixed the broken javadoc links
=> fixed broken links

mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/MapboxDirections.java, mapbox/libjava-services/src/test/java/com/mapbox/services/api/directions/v5/MapboxDirectionsTest.java
Closes: https://github.com/mapbox/mapbox-java/issues/341
=> fixed up radiuses Parameter

mapbox/libandroid-services/build.gradle, mapbox/libandroid-telemetry/build.gradle, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryLocationReceiver.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/http/TelemetryClient.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/location/AndroidLocationEngine.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/service/TelemetryService.java
=> Move timber dependency to libandroid-services

mapbox/app/src/main/java/com/mapbox/services/android/testapp/location/GoogleLocationEngine.java, mapbox/libandroid-services/src/main/java/com/mapbox/services/android/location/LostLocationEngine.java
Fixes https://github.com/mapbox/mapbox-java/issues/332 and fixes https://github.com/mapbox/mapbox-java/issues/324.
=> Only remove location updates when connected

CHANGELOG.md, mapbox/gradle.properties
See: https://github.com/mapbox/mapbox-java/issues/349.
=> Release 2.0.0-beta.2

mapbox/app/build.gradle, mapbox/app/src/main/java/com/mapbox/services/android/testapp/directions/DirectionsV5Activity.java, mapbox/dependencies.gradle, mapbox/libandroid-services/build.gradle, mapbox/libandroid-telemetry/build.gradle, mapbox/libandroid-ui/build.gradle, mapbox/libjava-core/build.gradle, mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/directions/v5/DirectionsServiceRx.java, mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/directions/v5/MapboxDirectionsRx.java, mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/distance/v1/DistanceServiceRx.java, mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/distance/v1/MapboxDistanceRx.java, mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/geocoding/v5/GeocodingServiceRx.java, mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/geocoding/v5/MapboxGeocodingRx.java, mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/mapmatching/v5/MapMatchingServiceRx.java, mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/mapmatching/v5/MapboxMapMatchingRx.java, mapbox/libjava-services-rx/src/test/java/com/mapbox/services/api/rx/directions/v5/MapboxDirectionsRxTest.java, mapbox/libjava-services-rx/src/test/java/com/mapbox/services/api/rx/distance/v1/MapboxDistanceRxTest.java, mapbox/libjava-services-rx/src/test/java/com/mapbox/services/api/rx/geocoding/v5/MapboxGeocodingRxTest.java, mapbox/libjava-services-rx/src/test/java/com/mapbox/services/api/rx/mapmatching/v5/MapboxMapMatchingRxTest.java
This PR does two things:
1. Centralize all deps in `dependencies.gradle`
2. Bump a few stable versions
=> Fix versioning

mapbox/libandroid-telemetry/build.gradle, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/http/TelemetryClient.java
=> Telemetry consumers set their user agent value

.gitignore, content/2.0.0/geocoder.md, content/2.0.0/getting_started.md, css/style.css, index.html, src/components/app.js, src/components/content.js, src/components/section.js, src/custom/content.js, src/custom/index.js
=> Documentation work

mapbox/app/src/main/java/com/mapbox/services/android/testapp/MainActivity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/directions/DirectionsV5Activity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/directions/RouteUtilsV5Activity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/distance/DistanceActivity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/geocoding/GeocodingReverseActivity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/nav/OffRouteDetectionActivity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/nav/SnapToRouteActivity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/staticimage/StaticImageActivity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/turf/TurfDestinationActivity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/turf/TurfDistanceActivity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/turf/TurfInsideActivity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/turf/TurfMidpointActivity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/utils/MapMatchingActivity.java, mapbox/libandroid-services/src/main/java/com/mapbox/services/android/navigation/v5/LocationUpdatedThread.java, mapbox/libandroid-services/src/main/java/com/mapbox/services/android/navigation/v5/MapboxNavigation.java, mapbox/libandroid-ui/src/main/java/com/mapbox/services/android/ui/geocoder/GeocoderAdapter.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/ServicesException.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/navigation/v5/RouteProgress.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/utils/turf/TurfException.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/utils/turf/TurfGrids.java, mapbox/libjava-services/src/test/java/com/mapbox/services/api/turf/TurfInvariantTest.java
=> make service and turf RuntimeExceptions

mapbox/app/src/main/java/com/mapbox/services/android/testapp/distance/DistanceActivity.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java, scripts/bitrise.yml
=> Firebase Test Lab CI integration for app module

CHANGELOG.md, mapbox/gradle.properties, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
References: https://github.com/mapbox/mapbox-java/issues/384.
cc: @cammace
=> Release MAS v2.0.0-beta.3

CHANGELOG.md, mapbox/dependencies.gradle, mapbox/gradle.properties
References https://github.com/mapbox/mapbox-java/issues/394.
cc: @cammace
=> Release MAS v2.0.0

mapbox/libandroid-services/gradle-javadoc.gradle, mapbox/libandroid-telemetry/gradle-javadoc.gradle, mapbox/libandroid-ui/gradle-javadoc.gradle, mapbox/libjava-core/gradle-javadoc.gradle, mapbox/libjava-geojson/gradle-javadoc.gradle, mapbox/libjava-services-rx/gradle-javadoc.gradle, mapbox/libjava-services/gradle-javadoc.gradle, mapbox/libjava-services/src/main/java/com/mapbox/services/api/navigation/v5/RouteUtils.java
Closes: https://github.com/mapbox/mapbox-java/issues/400
=> adds optional geometry precsion param to some methods

mapbox/app/src/main/AndroidManifest.xml, mapbox/app/src/main/java/com/mapbox/services/android/testapp/MainActivity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/distance/DistanceActivity.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/nav/NavigationActivity.java, mapbox/app/src/main/res/layout/activity_navigation_activity.xml, mapbox/app/src/main/res/values/strings.xml, mapbox/dependencies.gradle, mapbox/libandroid-services/src/main/java/com/mapbox/services/android/navigation/v5/MapboxNavigation.java, mapbox/libandroid-services/src/main/java/com/mapbox/services/android/navigation/v5/NavigationService.java
This PR brings a new sample activity to the test app that shows how to use the new navigation SDK on Android.
cc: @cammace
=> [WIP] Add sample activity implementing Navigation SDK

Makefile, mapbox/app/src/main/java/com/mapbox/services/android/testapp/MasApplication.java, mapbox/app/src/main/java/com/mapbox/services/android/testapp/nav/NavigationActivity.java, mapbox/libandroid-services/src/main/java/com/mapbox/services/android/navigation/v5/LocationUpdatedThread.java, mapbox/libandroid-services/src/main/java/com/mapbox/services/android/navigation/v5/NavigationService.java, mapbox/libandroid-services/src/main/java/com/mapbox/services/android/navigation/v5/NewRouteProgressListener.java, mapbox/libandroid-services/src/test/java/com/mapbox/services/android/navigation/v5/BaseNavigationTest.java, mapbox/libandroid-services/src/test/java/com/mapbox/services/android/navigation/v5/RouteProgressTest.java, mapbox/libandroid-services/src/test/resources/navigation.json, mapbox/libjava-services/src/main/java/com/mapbox/services/api/navigation/v5/RouteProgress.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/navigation/v5/RouteUtils.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/navigation/v5/models/RouteLegProgress.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/navigation/v5/models/RouteStepProgress.java
Closes https://github.com/mapbox/mapbox-java/issues/377
This makes several improvements to the routeProgress object including making it immutable. This also updates a few methods found in the LocationUpdateThread class.
=> Route progress immutable

mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/DirectionsRoute.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/DirectionsWaypoint.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/IntersectionLanes.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/LegStep.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/RouteLeg.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/StepIntersection.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/StepManeuver.java
In libjava-services, created setters for the following model classes of Directions Api to expose the setters to the users - 
-DirectionsRoute
-DirectionsWaypoint
-IntersectionLanes
-LegStep
-RouteLeg 
-StepIntersection
-StepManeuver
https://github.com/mapbox/mapbox-java/issues/368
=> Setters for the model classes of directions api

Makefile, mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/directionsmatrix/v1/DirectionsMatrixServiceRx.java, mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/directionsmatrix/v1/MapboxDirectionsMatrixRx.java, mapbox/libjava-services-rx/src/test/java/com/mapbox/services/api/rx/directionsmatrix/v1/MapboxDirectionsMatrixRxTest.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/MapboxDirections.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directionsmatrix/v1/DirectionsMatrixService.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directionsmatrix/v1/MapboxDirectionsMatrix.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directionsmatrix/v1/models/DirectionsMatrixResponse.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directionsmatrix/v1/models/package-info.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directionsmatrix/v1/package-info.java, mapbox/libjava-services/src/test/fixtures/directions_matrix_2x3.json, mapbox/libjava-services/src/test/fixtures/directions_matrix_3x3.json, mapbox/libjava-services/src/test/java/com/mapbox/services/api/directionsmatrix/v1/MapboxDirectionsMatrixTest.java
closes: https://github.com/mapbox/mapbox-java/issues/406
Adds support for the directions matrix v1 recently launched
=> Support for directions matrix

mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/http/TelemetryClient.java
Fixes https://github.com/mapbox/mapbox-java/issues/430.
=> Remove unnecessary log calls

mapbox/dependencies.gradle, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/location/AndroidLocationEngine.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/location/LocationEngine.java
Fixes https://github.com/mapbox/mapbox-java/issues/429.
=> Update LOST to latest version

mapbox/libandroid-services/src/main/AndroidManifest.xml, mapbox/libandroid-telemetry/src/main/AndroidManifest.xml, mapbox/libandroid-ui/src/main/AndroidManifest.xml
Fixes https://github.com/mapbox/mapbox-java/issues/434.
=> Remove unnecessary elements from the Manifest in Android libraries

mapbox/libandroid-services/gradle-javadoc.gradle, mapbox/libandroid-telemetry/gradle-javadoc.gradle, mapbox/libandroid-ui/gradle-javadoc.gradle, mapbox/libjava-core/src/main/java/com/mapbox/services/commons/utils/TextUtils.java, mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/directionsmatrix/v1/DirectionsMatrixServiceRx.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/DirectionsService.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/MapboxDirections.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/DirectionsResponse.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/DirectionsRoute.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/DirectionsWaypoint.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/IntersectionLanes.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/LegStep.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/RouteLeg.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/StepIntersection.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/StepManeuver.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directionsmatrix/v1/DirectionsMatrixService.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/directionsmatrix/v1/models/DirectionsMatrixResponse.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/optimizedtrips/v1/MapboxOptimizedTrips.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/optimizedtrips/v1/OptimizedTripsService.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/optimizedtrips/v1/models/OptimizedTripsResponse.java, mapbox/libjava-services/src/main/java/com/mapbox/services/api/staticimage/v1/models/StaticMarkerAnnotation.java
Resolves all missing javadoc and fixes since tags referencing `2.0.1`.
=> Missing javadoc added

mapbox/gradle.properties
https://github.com/mapbox/mapbox-java/issues/445
=> release 2.1

mapbox/build.gradle, mapbox/dependencies.gradle, mapbox/libandroid-services/src/main/java/com/mapbox/services/android/location/LostLocationEngine.java
Now the latest LOST SNAPSHOT might be fixing https://github.com/mapbox/mapbox-java/issues/401, we're gonna use this PR to start testing the fix.
This is the equivalent of https://github.com/mapbox/mapbox-gl-native/pull/8872.
cc: @cammace
=> Update to LOST 2.3.0 (SNAPSHOT)

mapbox/dependencies.gradle
This PR updates the LOST dependency to v3.0.0
cc/ @zugaldia @tobrun
=> Update Lost to final version 3.0.0

mapbox/build.gradle, mapbox/dependencies.gradle
This PR updates Gradle and the Mapbox SDK.
=> Update dependencies in preparation for release

README.md
Bumped the number in the repo's `README.md` file
=> Bumped up to 2.2.0-SNAPSHOT

mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/http/TelemetryClient.java
=> Add new SSL certs for 2018/2019

mapbox/dependencies.gradle
This PR updates the LOST dependency to v3.0.1 per https://github.com/mapzen/lost/issues/213#issuecomment-309542033
👀 @zugaldia @tobrun
=> Update Lost to version 3.0.1

CHANGELOG.md, mapbox/gradle.properties
References https://github.com/mapbox/mapbox-java/issues/487.
=> Release MAS 2.1.2

CHANGELOG.md, mapbox/gradle.properties
References: https://github.com/mapbox/mapbox-java/issues/494
cc: @tobrun
=> Release MAS v2.1.3

mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/permissions/PermissionsManager.java
=> Add check to determine if runtime permissions are required

mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
closes #520, haven't added a milestone.
=> add check for battery status not availlable

mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
Fixes https://github.com/mapbox/mapbox-java/issues/523.
=> Harden telemetry shutdown

mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/constants/TelemetryConstants.java
cc: @Guardiola31337 @tobrun @cammace
=> Add setter for session rotation time

CHANGELOG.md
- Updates `CHANGELOG.md` reflecting `v2.2.2` changes and missing ones from `v2.2.1`
👀 @zugaldia @cammace @tobrun
=> Release v2.2.2

mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/http/TelemetryClient.java
Adds a for loop which adds all the metadata for the events, not sure why this wasn't the way it was done the first place.
=> Map out all navigation events

mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxEvent.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/http/TelemetryClient.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/navigation/MapboxNavigationEvent.java
- Fixes missing `device` attribute for navigation events
👀 @ericrwolfe @cammace @zugaldia
=> Fix missing device attribute for navigation events

mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
- Adds `navigation.reroute` events support
👀 @zugaldia @electrostat @cammace @ericrwolfe
=> Add navigation reroute events support

mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
Change to public call to allow for events to be sent immediately.
=> Flush Navigation Events Manually

mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/utils/TelemetryUtils.java
Change from returning system volume level to returning the music volume level.
=> Get correct volume leve

mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/http/TelemetryClient.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/navigation/MapboxNavigationEvent.java
- Adds telem current `LocationEngine` being used track support
👀 @zugaldia @cammace @electrostat @ericrwolfe
=> Add telem current location engine being used track support

mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/http/TelemetryClient.java, mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/navigation/MapboxNavigationEvent.java
- Adds telem cancel `rating` and `comment` track support
👀 @ericrwolfe @zugaldia @danesfeder @electrostat
=> Add telem cancel rating and comment track support

CHANGELOG.md
- Addresses #628 
👀 @zugaldia @tobrun @danesfeder @cammace
=> Release 2.2.8

mapbox/build.gradle, mapbox/dependencies.gradle, mapbox/libandroid-telemetry/src/main/AndroidManifest.xml
- Downgrades `minSdkVersion` to 14
👀 @zugaldia @tobrun
=> Downgrade minimum sdk version to 14

mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
- Deactivates location engine when shutting down telemetry service
👀 @tobrun @electrostat @zugaldia
=> Deactivate location engine when shutting down telemetry service

CHANGELOG.md
- Addresses #637 
@zugaldia @tobrun @langsmith
=> Release 2.2.9

circle.yml
- Fixes CI image
- Removes unnecessary `Accept Android license` step from `release` job
👀 @cammace @tobrun
=> Fix CI image

services-geocoding/src/main/java/com/mapbox/geocoding/v5/models/CarmenFeature.java, services-geocoding/src/main/java/com/mapbox/geocoding/v5/models/GeocodingResponse.java, services-geocoding/src/test/java/com/mapbox/geocoding/v5/models/CarmenFeatureTest.java, services-geojson/src/main/java/com/mapbox/geojson/BoundingBox.java, services-geojson/src/main/java/com/mapbox/geojson/Feature.java, services-geojson/src/main/java/com/mapbox/geojson/FeatureCollection.java, services-geojson/src/main/java/com/mapbox/geojson/GeometryCollection.java, services-geojson/src/main/java/com/mapbox/geojson/LineString.java, services-geojson/src/main/java/com/mapbox/geojson/MultiLineString.java, services-geojson/src/main/java/com/mapbox/geojson/MultiPoint.java, services-geojson/src/main/java/com/mapbox/geojson/MultiPolygon.java, services-geojson/src/main/java/com/mapbox/geojson/Point.java, services-geojson/src/main/java/com/mapbox/geojson/Polygon.java
Closes #660 
I've opened https://github.com/mapbox/mapbox-java/issues/662 to track making the toJson method more generic so we don't have to fix every class in the future (shouldn't be a Semver change).
=> adds lower case with underscore rule to each object

Makefile
- Fixes `make: Nothing to be done for 'publish'.` adding tabs
👀 @cammace @zugaldia
=> Fix publish Makefile

CHANGELOG.md
- Addresses https://github.com/mapbox/mapbox-java/issues/672
👀 @cammace @danesfeder @zugaldia
=> Release 3.0.0-beta.1

build.gradle, gradle/dependencies.gradle, services-core/build.gradle, services-core/src/main/java/com/mapbox/core/constants/Constants.java, services-core/src/main/java/com/mapbox/core/utils/ApiCallHelper.java, services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsError.java
=> Adds support for BuildConfig file

services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
=> add missing return early statement in directions class

Makefile, samples/build.gradle, samples/src/main/java/com/mapbox/samples/BasicDirections.java, samples/src/main/java/com/mapbox/samples/BasicGeocoding.java, samples/src/main/java/com/mapbox/samples/BasicMapMatching.java, samples/src/main/java/com/mapbox/samples/BasicOptimization.java, samples/src/main/java/com/mapbox/samples/BasicStaticMap.java
Closes https://github.com/mapbox/mapbox-java/issues/652
Remove hardcoded access token and adds buildconfig task so we use the access token from the system environment variables.
=> adds buildConfig task to samples module so we can get access token from developers bash_profile

services-geojson/src/main/java/com/mapbox/geojson/FeatureCollection.java, services-geojson/src/main/java/com/mapbox/geojson/GeometryCollection.java, services-geojson/src/main/java/com/mapbox/geojson/MultiLineString.java, services-geojson/src/main/java/com/mapbox/geojson/MultiPolygon.java, services-geojson/src/test/java/com/mapbox/geojson/FeatureCollectionTest.java, services-geojson/src/test/java/com/mapbox/geojson/GeometryCollectionTest.java, services-geojson/src/test/java/com/mapbox/geojson/MultiLineStringTest.java, services-geojson/src/test/java/com/mapbox/geojson/MultiPolygonTest.java
=> Adds new static initializers to geojson collection objects

Makefile, services-matching/src/main/java/com/mapbox/api/matching/v5/MapMatchingService.java, services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java, services-matching/src/test/java/com/mapbox/api/matching/v5/MapboxMapMatchingTest.java
Add missing params to Mapbox Matching Builder
waypoints, roundaboutExits, voiceInstructions, bannerInstructions
Added tests
=> Add missing params to Mapbox Matching Builder

services-geojson/src/main/java/com/mapbox/geojson/FeatureCollection.java, services-geojson/src/main/java/com/mapbox/geojson/GeometryCollection.java, services-geojson/src/main/java/com/mapbox/geojson/LineString.java, services-geojson/src/main/java/com/mapbox/geojson/MultiLineString.java, services-geojson/src/main/java/com/mapbox/geojson/MultiPoint.java, services-geojson/src/main/java/com/mapbox/geojson/MultiPolygon.java, services-geojson/src/main/java/com/mapbox/geojson/Point.java, services-geojson/src/main/java/com/mapbox/geojson/Polygon.java, services-turf/src/test/java/com/mapbox/turf/TurfJoinsTest.java
This is partially addressing https://github.com/mapbox/mapbox-java/issues/710
=> Added back fromLngLats() that take double arrays for coordinates

README.md, gradle/sonarqube.gradle
Project can be found publicly here: https://sonarcloud.io/dashboard?id=mapbox-java-services%3Amaster
=> moved to use Sonarcloud

services-core/src/main/java/com/mapbox/core/MapboxService.java
=> Make getOkHttpClient synchronized

services-turf/src/main/java/com/mapbox/turf/TurfClassification.java, services-turf/src/main/java/com/mapbox/turf/TurfConstants.java, services-turf/src/main/java/com/mapbox/turf/TurfConversion.java, services-turf/src/main/java/com/mapbox/turf/TurfJoins.java, services-turf/src/main/java/com/mapbox/turf/TurfMeasurement.java, services-turf/src/main/java/com/mapbox/turf/TurfMisc.java, services-turf/src/test/java/com/mapbox/turf/TurfClassificationTest.java, services-turf/src/test/java/com/mapbox/turf/TurfConversionTest.java, services-turf/src/test/java/com/mapbox/turf/TurfJoinsTest.java, services-turf/src/test/java/com/mapbox/turf/TurfMeasurementTest.java, services-turf/src/test/java/com/mapbox/turf/TurfMiscTest.java
=> Turf methods name changes

services-directions/src/main/java/com/mapbox/api/directions/v5/DirectionsCriteria.java
=> added tunnel and restricted to possible values of exclude criteria

CHANGELOG.md
bumped to 3.0.0 in individual modules
changed circle ci script to release 3.0.0
=> release 3.0.0

CHANGELOG.md, circle.yml, gradle.properties, services-core/gradle.properties, services-geojson/gradle.properties, services-turf/gradle.properties, services/gradle.properties
=> Release v3.0.1

samples/src/main/java/com/mapbox/samples/BasicDirections.java, services-geojson/src/main/java/com/mapbox/geojson/Polygon.java, services-geojson/src/main/java/com/mapbox/geojson/utils/PolylineUtils.java
Follow up on external PR in #767
=> Issue 653:Missing java docs

samples/src/main/java/com/mapbox/samples/BasicStaticMap.java, services-core/src/main/java/com/mapbox/core/utils/ColorUtils.java, services-staticmap/src/main/java/com/mapbox/api/staticmap/v1/models/StaticMarkerAnnotation.java, services-staticmap/src/main/java/com/mapbox/api/staticmap/v1/models/StaticPolylineAnnotation.java, services-staticmap/src/test/java/com/mapbox/api/staticmap/v1/MapboxStaticMapTest.java, services-staticmap/src/test/java/com/mapbox/api/staticmap/v1/models/StaticMarkerAnnotationTest.java
=> java.awt.Color is not available on Android platform

README.md
This pr fixes broken links and does some renaming
=> README update/fixes

services-turf/README.md
This pr adds a basic README file for the Turf library.
=> Added Turf README

services-geojson/src/main/java/com/mapbox/geojson/Point.java
* `type` must be lowercase
* it's → its
=> Fix Point Javadoc

services-staticmap/src/main/java/com/mapbox/api/staticmap/v1/MapboxStaticMap.java, services-staticmap/src/main/java/com/mapbox/api/staticmap/v1/models/StaticMarkerAnnotation.java, services-staticmap/src/test/java/com/mapbox/api/staticmap/v1/models/StaticMarkerAnnotationTest.java
porting external PR #836
cc @freszu
=> Static image marker fixes 

services-staticmap/src/main/java/com/mapbox/api/staticmap/v1/MapboxStaticMap.java
this pr fixes a typo in the javadocs
=> StaticMap javadocs typo fix

services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/GeocodingCriteria.java, services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/GeocodingService.java, services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/MapboxGeocoding.java, services-geocoding/src/test/java/com/mapbox/api/geocoding/v5/MapboxGeocodingTest.java
=> added reverseMode parameter to Geocoading Service

gradle/dependencies.gradle, services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java, services-geocoding/src/test/java/com/mapbox/api/geocoding/v5/MapboxGeocodingTest.java, services-geocoding/src/test/java/com/mapbox/api/geocoding/v5/models/CarmenContextTest.java, services-geocoding/src/test/java/com/mapbox/api/geocoding/v5/models/CarmenFeatureTest.java, services-geocoding/src/test/java/com/mapbox/api/geocoding/v5/models/GeocodingResponseTest.java, services-geojson/src/test/java/com/mapbox/geojson/utils/PolylineUtilsTest.java, services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java, services-matching/src/test/java/com/mapbox/api/matching/v5/MapboxMapMatchingTest.java, services-speech/build.gradle
closes #850 
upgraded dependencies.
Due to a New Version of errorprone had to update:
http://errorprone.info/bugpattern/ObjectToString
http://errorprone.info/bugpattern/UseCorrectAssertInTests
http://errorprone.info/bugpattern/StringSplitter
=> upgdraded dependecies

services-staticmap/src/main/java/com/mapbox/api/staticmap/v1/models/StaticPolylineAnnotation.java, services-staticmap/src/test/java/com/mapbox/api/staticmap/v1/models/StaticPolylineAnnotationTest.java
=> fixed typo in static map annotations and added tests for map annotations

services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsJsonObject.java, services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsResponse.java, services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsRoute.java, services-directions/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java, services-directions/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
RouteOptions List<Point> should be serialized as double[][]
closes #864
=> missing Point deserializer 

README.md
=> Update README for 3.4.0 Release

CHANGELOG.md
=> release 3.4.1

README.md
=> Remove mention of repo test app from root README

services-directions/src/main/java/com/mapbox/api/directions/v5/models/BannerText.java, services-directions/src/main/java/com/mapbox/api/directions/v5/models/StepManeuver.java
=> Added StepManeuver.Type for ease of use

services-speech/src/main/java/com/mapbox/api/speech/v1/MapboxSpeech.java
- Adds `interceptor` and `networkInterceptor` support to `MapboxSpeech`
=> Add interceptor and network interceptor support to Mapbox Speech

services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java, services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsResponse.java, services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/MapboxGeocoding.java, services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/models/CarmenContext.java, services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/models/CarmenFeature.java, services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java, services-matching/src/main/java/com/mapbox/api/matching/v5/models/MapMatchingResponse.java, services-matrix/src/main/java/com/mapbox/api/matrix/v1/MapboxMatrix.java, services-optimization/src/main/java/com/mapbox/api/optimization/v1/MapboxOptimization.java, services-staticmap/src/main/java/com/mapbox/api/staticmap/v1/MapboxStaticMap.java, services-tilequery/src/main/java/com/mapbox/api/tilequery/MapboxTilequery.java
🚧  Do not merge until API documentation changes land 🚧 
This PR updates links to the API docs to match the new URL structure.
@langsmith to review please 🙏 
cc @mapbox/docs
=> [DNM] Updates URLs for API documentation for mapbox-java

build.gradle, samples/build.gradle, services-core/build.gradle, services-directions/build.gradle, services-geocoding/build.gradle, services-geojson/build.gradle, services-matching/build.gradle, services-matrix/build.gradle, services-optimization/build.gradle, services-route-tiles/build.gradle, services-speech/build.gradle, services-staticmap/build.gradle, services-tilequery/build.gradle, services-turf/build.gradle, services/build.gradle
Refs https://github.com/mapbox/mapbox-gl-native/issues/13598.
=> Prepare the repository as Maps SDK vendor

build.gradle
remove android tooling
addresses #983
=> remove android tooling

CHANGELOG.md
=> updated changelog for 4.8.0-apha.2 release

CHANGELOG.md
Release v4.8.0-alpha.3 for Navigation for walking options testing
=> Release v4.8.0 alpha.3

Makefile
When running tests with `make test` and if a test fails, we aren't seeing any actionable output. Adding the `-i` flag shows the content why an assertion failed. 
```
com.mapbox.turf.TurfMeasurementTest > centerFromImbalancedPolygon FAILED
java.lang.AssertionError: Features should match expected:<FeatureCollection{type=FeatureCollection, bbox=null, features=[Feature{type=Feature, bbox=null, id=null, geometry=Point{type=Point, bbox=null, coordinates=[4.851944446563721, 45.778762648296855]}, properties={"marker-symbol":"star","marker-color":"#F00"}}, Feature{type=Feature, bbox=null, id=null, geometry=Polygon{type=Polygon, bbox=null, coordinates=[[Point{type=Point, bbox=null, coordinates=[4.854240417480469, 45.77258200374433]}, Point{type=Point, bbox=null, coordinates=[4.8445844650268555, …
```
=> Show more test output

services-directions-refresh/src/main/java/com/mapbox/api/directionsrefresh/v1/MapboxDirectionsRefresh.java
- Adds `Interceptor` to set in the `OkHttp` client support to Directions Refresh API
- Enables Debug logging
=> Add Interceptor support to Directions Refresh API and enable Debug logging

build.gradle
=> keep *.java - files in source.jar artifacts (shoud fix #1053)

CHANGELOG.md
Changelog entries needed hyperlinks to the actual pull request. No, I didn't do this one-by-one. The power of find all + replace 😛
=> Added hyperlinks to changelog entries that needed them

CHANGELOG.md
This pr makes changes as part of the 4.9.0 stable release of the Mapbox Java SDK: https://github.com/mapbox/mapbox-java/issues/1070
=> Changelog updates for stable 4.9.0 release

CHANGELOG.md, README.md
Addresses https://github.com/mapbox/mapbox-java/issues/1100
=> Release 5.0.0

CHANGELOG.md
Addresses https://github.com/mapbox/mapbox-java/issues/1113
=> Release 5.1.0-beta.1

services-staticmap/src/main/java/com/mapbox/api/staticmap/v1/StaticMapCriteria.java
This pr is a follow up to #1109 and specifically addresses @Guardiola31337 's comment about nav style versions at https://github.com/mapbox/mapbox-java/pull/1109#pullrequestreview-348209578
=> Bumped StaticMapCriteria guidance day and night versions to v4

CHANGELOG.md
Addresses https://github.com/mapbox/mapbox-java/issues/1131
=> Release 5.1.0-beta.2

CHANGELOG.md, README.md
=> Release 5.1.0

services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/DirectionsJsonObject.java
Duplicate of @arturdryomov's https://github.com/mapbox/mapbox-java/pull/1105. Needed to duplicate to get CircleCI to run and pass.
=> Fix typo in DirectionsJsonObject documentation

services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/BannerText.java, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/BannerView.java, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/ManeuverModifier.java, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/StepManeuver.java, services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/StepManeuverTest.java
Resolves https://github.com/mapbox/mapbox-java/issues/1141
Adding constants for step maneuver modifier
=> Add step maneuver modifier constants

services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/ManeuverModifier.java
Update ManeuverModifier.Type to be public
=> Update maneuver modifier type to be public

CHANGELOG.md
Addresses https://github.com/mapbox/mapbox-java/issues/1147
=> Update changelog for 5.2.1

CHANGELOG.md, README.md
Addresses [#1155](https://github.com/mapbox/mapbox-java/issues/1155)
=> Release 5.3.0

CHANGELOG.md, README.md
Related to https://github.com/mapbox/mapbox-java/issues/1162
=> Release 5.4.1

CHANGELOG.md, README.md, gradle.properties
Related to https://github.com/mapbox/mapbox-java/issues/1175
=> Release 5.5.0

services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/MapboxStreetsV8.java, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/StepIntersection.java, services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/MapboxStreetsV8Test.java, services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/StepIntersectionTest.java
added fields
`isUrban`
`Street`
=> Intersection fields

CHANGELOG.md, README.md, gradle.properties
=> Release 5.6.0

gradle/dependencies.gradle
closes https://github.com/mapbox/mapbox-java/issues/1193
=> bump retrofit to 4.7.2 to be android API 30 compatible

services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/StepIntersection.java, services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/StepIntersectionTest.java
=> tunnelName field

services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/Congestion.java, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/Incident.java, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/LegStep.java, services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/CongestionTest.java, services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/IncidentTest.java
Directions models: introduce Incident and Congestion as a part of Directions  API
=> Directions models: Incident and Congestion

CHANGELOG.md
=> release 5.8.0-beta.1

services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/IntersectionLanes.java, services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/IntersectionLanesTest.java
https://github.com/mapbox/mapbox-java/pull/1217 follow up. There will only be one valid indication, not a subset of indications.
=> Fix valid indication to provide a single possibility

services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/BannerComponents.java, services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/BannerComponentTest.java
=> add subType to bannerComponents

.gitignore
`publisher-production`' .gitignore
=> publisher production gitignore

CHANGELOG.md
Add Changelog for `5.8.0-beta.5` release
=> Add Changelog for 5.8.0-beta.5 release

CHANGELOG.md
Added Changelog for 5.9.0-alpha.1 release
=> Added changelog for 5.9.0-alpha.1 release

.gitignore, cloudformation/ci.template, gradle/publish.gradle
Resolves https://github.com/mapbox/mapbox-java/issues/1235
Having trouble authenticating a putObject with https://mapbox.askspoke.com/next/requests/14060
=> Add cloudformation for publishing to sdk-registry

CHANGELOG.md
Changelog 5.9.0-alpha.2 and 5.9.0-alpha.3
=> Changelog 5.9.0-alpha.2 and 5.9.0-alpha.3

CHANGELOG.md
Updating change log for release.
=> Updating change log for release.

services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java, services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
add a fun to add a single snapping closure item
closes #1254
=> addSnappingClosure fun

services-directions-models/src/main/java/com/mapbox/api/directions/v5/DirectionsCriteria.java, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/BannerComponents.java, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/Incident.java, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/LegStep.java, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/ManeuverModifier.java, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/SpeedLimit.java, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/StepManeuver.java, services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/GeocodingCriteria.java, services-isochrone/src/main/java/com/mapbox/api/isochrone/IsochroneCriteria.java, services-staticmap/src/main/java/com/mapbox/api/staticmap/v1/StaticMapCriteria.java, services-tilequery/src/main/java/com/mapbox/api/tilequery/TilequeryCriteria.java, services-turf/src/main/java/com/mapbox/turf/TurfConstants.java
`Def`s' retention policy review
Closes #1259
=> `Def`s retention policy review

services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/Closure.java
- Replaces `Closure` `@Nullable` annotations by `@NonNull`
Fixes #1266 
cc @danpat
=> Replace `Closure` `@Nullable` annotations by `@NonNull`

services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/DirectionsRoute.java, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java, services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/DirectionsRouteTest.java
This refactors the access token in the RouteOptions to be non-nullable again by first deserializing the json into a generic data structure, appending the provided token, and only then transforming into the type-safe RouteOptions object.
Refs https://github.com/mapbox/mapbox-java/pull/1267.
=> make the access token non-nullable in RouteOptions

build.gradle, gradle/dependencies.gradle
=> Bump okhttp to 4.9.0

services-directions-models/src/main/java/com/mapbox/api/directions/v5/DirectionsCriteria.java, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/LegAnnotation.java, services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/LegAnnotationTest.java
=> add congestion numeric support to leg annotation

services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
Tailwork from #1296 https://github.com/mapbox/mapbox-java/pull/1296#pullrequestreview-762451997
=> Remove unnecessary comment from Javadocs

CHANGELOG.md
=> Changelog v6.0.0-alpha.7

services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java, services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
=> RouteOptions toUrl()

services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java, services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
do not add null values to the url
=> RouteOptions toUrl fix

CHANGELOG.md, README.md
Update of change log and readme for release of 6.0.1.
=> Update of change log and readme for release of 6.0.1.

CHANGELOG.md, services-directions-models/src/main/java/com/mapbox/api/directions/v5/DirectionsCriteria.java
Implementation of the #1309 and the #1308
=> Added exclude unpaved and cash only tolls options

gradle/dependencies.gradle, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/BannerComponents.java, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/MapboxShield.java, services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/BannerComponentTest.java, services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/MapboxShieldTest.java
The PR is the first in series for addressing mapbox designed route shields.
=> Add support for mapbox designed route shields.

services-optimization/src/main/java/com/mapbox/api/optimization/v1/MapboxOptimization.java, services-optimization/src/test/java/com/mapbox/api/optimization/v1/MapboxOptimizationTest.java
- Removes Optimization coordinates limit check
Fixes https://github.com/mapbox/mapbox-java/issues/1338 #1157 
cc @PureW @soleary91 @pjleonard37 @danpat
=> Remove Optimization coordinates limit check

.circleci/config.yml
Refs mapbox/navigation-sdks#1302.
=> update tokens usage

.circleci/config.yml, Makefile, gradle/dependencies.gradle
Updated sdk registry plugin. Used the Navigation Android SDK as an example of usage.
=> Update sdk registry plugin

services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/StepIntersection.java, services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/StepIntersectionTest.java
=> added railway crossings to step intersection

Makefile
=> docs: added `directions-models` and `directions-refresh-models`

scripts/publish_api_docs_android.sh
=> publish_api_docs_android.sh fix: create parent folders if needed

CHANGELOG.md, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/DirectionsJsonObject.java, services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/DirectionsResponseTest.java
The PR adds API to access unrecognised fields
=> API to access unrecognized fields

CHANGELOG.md, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RestStop.java, services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/StepIntersectionTest.java
Refs https://docs.mapbox.com/api/navigation/directions/#route-step-object/.
=> exposed RestStop#name

CHANGELOG.md
CP https://github.com/mapbox/mapbox-java/pull/1473
=> CP changelog for v6.7.0

gradle/artifact-settings.gradle
Closes https://github.com/mapbox/mapbox-java/issues/1467.
=> keep snapshot name matching latest pre-release name

CHANGELOG.md
Update changelog to remove private api
=> Update changelog to remove private api

CHANGELOG.md
=> Changelog for `v6.8.0-beta.2`

services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/Closure.java, services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/Incident.java
=> NAVAND-646: specify in Incident and Closure docs that indices are leg-wise

.circleci/config.yml, services-cli/README.md, services-cli/src/main/kotlin/com.mapbox.services.cli/MapboxJavaCli.kt, services-cli/src/main/kotlin/com/mapbox/services/cli/validator/DirectionsResponseValidator.kt, services-cli/src/main/kotlin/com/mapbox/services/cli/validator/ValidatorResult.kt, services-cli/src/test/kotlin/com/mapbox/services/cli/validator/DirectionsResponseValidatorTest.kt, services-cli/src/test/kotlin/com/mapbox/services/cli/validator/MapboxJavaCliTest.kt, services-cli/src/test/kotlin/com/mapbox/services/cli/validator/SystemExitRule.kt
JIRA: [NAVAND-1714](https://mapbox.atlassian.net/browse/NAVAND-1714)
What has been done:
* handle string input: -j "example json file"
* exit with code 1 when failed verification
* exit also with code 1 on back conversion: -c
* pretty print result: -p
* updated tests
Example:
[NAVAND-1714]: https://mapbox.atlassian.net/browse/NAVAND-1714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [NAVAND-1714] Upgrade services-cli

.circleci/config.yml, services-cli/src/main/kotlin/com.mapbox.services.cli/MapboxJavaCli.kt, services-cli/src/main/kotlin/com/mapbox/services/cli/validator/DirectionsResponseValidator.kt, services-cli/src/main/kotlin/com/mapbox/services/cli/validator/ValidatorResult.kt
Changes:
* handle input from Stdin
* export to s3
=> [NAVAND-3174] Upgrade services-cli

CHANGELOG.md, build.gradle, gradle/dependencies.gradle
https://mapbox.atlassian.net/browse/NAVAND-4936.
Adopting https://github.com/mapbox/auto-value-gson/releases/tag/mapbox-v0.0.2
=> auto-value-gson 0.0.2

CHANGELOG.md, gradle/dependencies.gradle, services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/SingleElementSafeListTypeAdapter.java
autoValueGson PR: https://github.com/mapbox/auto-value-gson/pull/6
=> bump autoValueGson and gson versions
