mapbox/mapbox-java

- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/custom/GeometryDeserializer.java
- libjava/lib/src/test/java/com/mapbox/services/geojson/FeatureCollectionTest.java
- libjava/lib/src/test/java/com/mapbox/services/geojson/FeatureTest.java
- libjava/lib/src/test/java/com/mapbox/services/geojson/GeometryCollectionTest.java
- scripts/bitrise.yml
Fixes #41.
Turns out there was an actual bug in the `GeometryDeserializer` object after the package was moved.
> Fixes geojson GeometryDeserializer.java and tests

- libjava/lib/src/main/java/com/mapbox/services/staticimage/v1/MapboxStaticImage.java
- libjava/lib/src/test/java/com/mapbox/services/staticimage/v1/MapboxStaticImageTest.java
This PR fixes three proposed improvement to the Static Image API service. Namely:
1. Provide option to specify position as Position #65
2. Validate image dimensions on value range #67
3. Add precision setter on builder #69
/cc: @ivovandongen @cammace
> Improvements to Static Image API service

- libandroid/lib/build.gradle
Fixes https://github.com/mapbox/mapbox-java/issues/126.
Note that this does not affect the TestApp, only the library, as the TestApp has API 15 requirements in LOST and the Mapbox SDK.
> Lower api level requirement to API 14

- libandroid/lib/src/main/java/com/mapbox/services/android/Constants.java
- libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/AndroidGeocoder.java
- libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/GeocoderUtils.java
- libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/ui/GeocoderAdapter.java
- libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/ui/GeocoderAutoCompleteView.java
- libandroid/lib/src/main/java/com/mapbox/services/android/utils/PermissionsUtils.java
- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/BaseFeatureCollection.java
- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/Feature.java
- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/FeatureCollection.java
- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/GeoJSON.java
- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/Geometry.java
- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/GeometryCollection.java
- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/LineString.java
- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/MultiLineString.java
- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/MultiPoint.java
- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/MultiPolygon.java
- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/Point.java
- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/Polygon.java
- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/custom/GeometryDeserializer.java
- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/custom/PositionDeserializer.java
- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/custom/PositionSerializer.java
- libjava/lib/src/main/java/com/mapbox/services/commons/turf/models/package-info.java
- libjava/lib/src/main/java/com/mapbox/services/commons/turf/package-info.java
- libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/gson/package-info.java
- libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/gson/package-info.java
- libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/models/package-info.java
- libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/package-info.java
Only outputting 5 warnings now for libandroid javadoc:
```
/Users/cameron/Mapbox/mapbox-java/libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/ui/GeocoderAutoCompleteView.java:12: error: cannot find symbol
import com.mapbox.services.android.R;
^
symbol:   class R
location: package com.mapbox.services.android
/Users/cameron/Mapbox/mapbox-java/libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/AndroidGeocoder.java:68: warning: no @return
public static boolean isPresent() {
^
/Users/cameron/Mapbox/mapbox-java/libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/AndroidGeocoder.java:96: warning: no @throws for com.mapbox.services.commons.ServicesException
public List<Address> getFromLocation(double latitude, double longitude, int maxResults)
^ …
```
> added missing javadoc and fixed errors

- libjava/lib/build.gradle
- libjava/lib/src/main/java/com/mapbox/services/commons/MapboxBuilder.java
- libjava/lib/src/main/java/com/mapbox/services/commons/ServicesException.java
- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/Feature.java
- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/custom/GeometryDeserializer.java
- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/custom/PositionDeserializer.java
- libjava/lib/src/main/java/com/mapbox/services/commons/models/Position.java
- libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfGrids.java
- libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfHelpers.java
- libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfInvariant.java
- libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfJoins.java
- libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfMeasurement.java
- libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfMisc.java
- libjava/lib/src/main/java/com/mapbox/services/directions/v4/DirectionsService.java
- libjava/lib/src/main/java/com/mapbox/services/directions/v4/MapboxDirections.java
- libjava/lib/src/main/java/com/mapbox/services/directions/v5/MapboxDirections.java
- libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/GeocodingCriteria.java
- libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/GeocodingService.java
- libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/MapboxGeocoding.java
- libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/gson/CarmenGeometryDeserializer.java
- libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/models/CarmenContext.java
- libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/models/CarmenFeature.java
- libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/models/CarmenFeatureCollection.java
- libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/models/GeocodingResponse.java
- libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/MapMatchingService.java
- libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/MapboxMapMatching.java
- libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/gson/MapMatchingGeometryDeserializer.java
- libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/models/MapMatchingResponse.java
- libjava/lib/src/main/java/com/mapbox/services/staticimage/v1/MapboxStaticImage.java
libjava now produces 0 errors or warnings. The problem was missing tags and tag descriptions among other things. Every public method now has javadoc.
I've also added a task in gradle to build the java doc:
```groovy
task JavadocGeneration(type: Javadoc) {
source = sourceSets.main.allJava
failOnError = false
classpath = configurations.compile
}
```
cc: @zugaldia
> Javadoc added and fixed

- libandroid/lib/build.gradle
We were missing `consumerProguardFiles 'proguard-rules.pro'` and the lib build gradle file. This should use the libraries progaurd-rules.pro file which includes:
```pro 
#MAS Data Models
-keep class com.mapbox.services.directions.v4.models.** { *; }
-keep class com.mapbox.services.directions.v5.models.** { *; }
-keep class com.mapbox.services.geocoding.v5.models.** { *; }
```
Closes #178 
cc: @zugaldia @tobrun
> fixed progaurd issue

- libandroid/app/src/main/AndroidManifest.xml
- libandroid/app/src/main/java/com/mapbox/services/android/testapp/MainActivity.java
- libandroid/app/src/main/java/com/mapbox/services/android/testapp/directions/DirectionsV5Activity.java
- libandroid/app/src/main/java/com/mapbox/services/android/testapp/directions/RouteUtilsV5Activity.java
- libandroid/app/src/main/res/drawable/ic_my_location_black_24dp.xml
- libandroid/app/src/main/res/layout/activity_route_utils_v5.xml
- libandroid/app/src/main/res/layout/content_route_utils_v5.xml
- libandroid/app/src/main/res/values/strings.xml
- libandroid/lib/build.gradle
- libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfMisc.java
- libjava/lib/src/main/java/com/mapbox/services/navigation/v5/RouteUtils.java
- libjava/lib/src/test/java/com/mapbox/services/navigation/v5/RouteUtilsTest.java
This PR brings a new `RouteUtils` class that brings some Turf-powered methods to obtain situational information from a `RouteLeg` object. To some extend, this a partial refactor and port to Java of @bsudekum 's work on [`navigation.js`](https://github.com/mapbox/navigation.js).
Particularly, this PR includes the following methods:
- `isInStep`: Given a position, a route, and a step index, determines if the position is close to the given step (within a customizable threshold).
- `getDistanceToStep`: Given a position, a route, and a step index, determines the distance between the position and the closest point in the given step.
- `getSnapToRoute`: Given a position, a route, and a step index, determines the closest point in the given step
- `isOffRoute`: Given a position and a route, …
> Bring RouteUtils class to simplify work with RouteLeg objects

- libandroid/CHANGELOG.md
- libandroid/lib/build.gradle
- libjava/CHANGELOG.md
This PR fixes an issue with Javadoc generation as described in https://github.com/chrisbanes/gradle-mvn-push/issues/43#issuecomment-84140513.
It also brings a dependency in `libandroid` back to `mapbox-java-services:2.0.0-SNAPSHOT` instead of `compile project(':libjava')`. This was inadvertingly introduced by https://github.com/mapbox/mapbox-java/pull/180.
/cc: @cammace
> Release v1.3.0

- libjava/lib/src/main/java/com/mapbox/services/commons/geojson/Feature.java
- libjava/lib/src/test/java/com/mapbox/services/geojson/FeatureTest.java
GSON ignores fields with `null` values during serialization. Setting empty `properties` as a `new JsonObject ()` makes sure the serialized JSON includes the `"properties":{}` string.
Fixes https://github.com/mapbox/mapbox-gl-native/issues/6240.
/cc: @cammace
> Make sure feature properties are properly serialized

- Makefile
- libjava/lib/src/test/fixtures/geocoding.json
- libjava/lib/src/test/fixtures/geocoding_country_not_supported.json
- libjava/lib/src/test/fixtures/geocoding_reverse.json
- libjava/lib/src/test/java/com/mapbox/services/geocoding/v5/MapboxGeocodingReverseTest.java
- libjava/lib/src/test/java/com/mapbox/services/geocoding/v5/MapboxGeocodingTest.java
Closes #167 
The geocoding doesn't crash since we are still given a response by the Geocoding API, it just contains no results. 
cc: @mapbox/android for review
> added country not supported test

- libandroid/app/src/main/java/com/mapbox/services/android/testapp/geocoding/GeocodingWidgetActivity.java
- libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/ui/GeocoderAdapter.java
- libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/ui/GeocoderAutoCompleteView.java
- libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/GeocodingService.java
- libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/MapboxGeocoding.java
We are missing a few options/parameters the geocoder gives you. This PR adds `limit` and exposes `country` in the auto complete widget. Still need to add `landmark`.
cc: @zugaldia
> Updates Geocoding to match API

- libandroid/app/src/main/java/com/mapbox/services/android/testapp/geocoding/GeocodingWidgetActivity.java
- libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/ui/GeocoderAdapter.java
- libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/ui/GeocoderAutoCompleteView.java
Closes #206
cc: @ivovandongen for review
> Added cancel method to autocomplete widget

- libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfMisc.java
- libjava/lib/src/test/java/com/mapbox/services/turf/TurfMiscTest.java
We were missing test for  [`Turf.Misc#pointOnLine()`](https://github.com/mapbox/mapbox-java/blob/master/libjava/lib/src/main/java/com/mapbox/services/commons/turf/TurfMisc.java#L90).
cc: @ivovandongen @zugaldia
> Turf Point On Line fixed and test added

- libandroid/app/build.gradle
- libandroid/app/gradle-dexcount.gradle
- libandroid/build.gradle
Added this [gradle plugin](https://github.com/KeepSafe/dexcount-gradle-plugin) which will output the dex method count every time you build the testapp. Output looks like this:
it also outputs a bunch of cool stuff here: `libandroid/app/build/outputs/dexcount` Including an interactive chart you can open in browser:
and a list with the package and method count for each:
```
methods  fields   package/class name
3        0        <unnamed>
20896    9297     android
6        0        android.accessibilityservice
41       0        android.animation
224      29       android.app
2        0        android.appwidget
267      33       android.content
24       23       android.content.pm
97       10       android.content.res
30       0        android.database
312      46       android.graphics
110 …
```
> Added gradle plugin that gives dex count every build

- libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/ui/GeocoderAdapter.java
- libandroid/lib/src/main/java/com/mapbox/services/android/geocoder/ui/GeocoderAutoCompleteView.java
- libandroid/lib/src/main/res/values/attrs.xml
> Geocoding autocomplete widget fixes

- libjava/lib/src/main/java/com/mapbox/services/navigation/v5/RouteUtils.java
- libjava/lib/src/test/java/com/mapbox/services/navigation/v5/RouteUtilsTest.java
It seems to make more sense to choose the furthest-ahead step when a given position is equidistant to multiple steps.
> Make RouteUtils.getClosestStep() choose furthest step in case of ties

- libandroid/app/build.gradle
- libandroid/app/proguard-rules.pro
- libandroid/lib/proguard-rules.pro
- libjava/lib/build.gradle
Closes https://github.com/mapbox/mapbox-java/issues/178
For some reason i'm running into this error when trying to build:
```
Information:Gradle tasks [:app:assembleDebug]
Warning:rx.internal.util.unsafe.BaseLinkedQueueConsumerNodeRef: can't find referenced class sun.misc.Unsafe
Warning:rx.internal.util.unsafe.BaseLinkedQueueProducerNodeRef: can't find referenced class sun.misc.Unsafe
Warning:rx.internal.util.unsafe.ConcurrentCircularArrayQueue: can't find referenced class sun.misc.Unsafe
Warning:rx.internal.util.unsafe.ConcurrentSequencedCircularArrayQueue: can't find referenced class sun.misc.Unsafe
Warning:rx.internal.util.unsafe.MpmcArrayQueueConsumerField: can't find referenced class sun.misc.Unsafe
Warning:rx.internal.util.unsafe.MpmcArrayQueueProducerField: can't find referenced …
```
> Added Proguard rules

- libandroid/app/build.gradle
Follow up on #245, where CI failed on using the Snapshot instead of the stable dependency from Mapbox GL Native. cc @cammace.
> use stable version of Mapbox GL Native dependency

- libjava/lib/src/main/java/com/mapbox/services/commons/MapboxBuilder.java
- libjava/lib/src/main/java/com/mapbox/services/directions/v4/MapboxDirections.java
- libjava/lib/src/main/java/com/mapbox/services/directions/v5/MapboxDirections.java
- libjava/lib/src/main/java/com/mapbox/services/distance/v1/MapboxDistance.java
- libjava/lib/src/main/java/com/mapbox/services/geocoding/v5/MapboxGeocoding.java
- libjava/lib/src/main/java/com/mapbox/services/mapmatching/v4/MapboxMapMatching.java
- libjava/lib/src/main/java/com/mapbox/services/staticimage/v1/MapboxStaticImage.java
- libjava/lib/src/test/java/com/mapbox/services/directions/v5/MapboxDirectionsTest.java
- libjava/lib/src/test/java/com/mapbox/services/distance/v1/MapboxDistanceTest.java
- libjava/lib/src/test/java/com/mapbox/services/geocoding/v5/MapboxGeocodingReverseTest.java
- libjava/lib/src/test/java/com/mapbox/services/geocoding/v5/MapboxGeocodingTest.java
- libjava/lib/src/test/java/com/mapbox/services/mapmatching/v4/MapboxMapMatchingTest.java
> [android] - make changing base url a part of public API.

- mapbox/dependencies.gradle
The CI bots on this repo were having the same issues as the one on gl-native in mapbox/mapbox-gl-native#7729. This PR upgrades the build tools to a bitrise supported version. After merging we need to publish a new snapshot to allow projects using this dependency to be build on CI.
Review @cammace
> [android] - upgrade to a bitrise compatible buildtools version

- mapbox/libjava-services/src/main/java/com/mapbox/services/api/geocoding/v5/models/CarmenFeature.java
- mapbox/libjava-services/src/test/fixtures/geocoder_tofromjson.json
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/geocoding/v5/CarmenFeatureTest.java
Closes: https://github.com/mapbox/mapbox-java/issues/278
Carmen Feature was using the `fromJson()` method found in the Feature.class. This method was returning a Feature object and not a Carmen. To get around this, I added a fromJson method to Carmen Feature.
> Added fromjson test and method for carmen feature

- Makefile
- mapbox/app/src/main/java/com/mapbox/services/android/testapp/location/GoogleLocationEngine.java
- mapbox/app/src/main/java/com/mapbox/services/android/testapp/location/LocationEngineActivity.java
- mapbox/app/src/main/java/com/mapbox/services/android/testapp/location/LostLocationEngine.java
- mapbox/app/src/main/java/com/mapbox/services/android/testapp/location/MockLocationEngine.java
- mapbox/app/src/main/res/values/strings.xml
- mapbox/libandroid-telemetry/build.gradle
- mapbox/libandroid-telemetry/src/main/AndroidManifest.xml
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxEvent.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryConstants.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryException.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryLocationReceiver.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/backoff/ExponentialBackoff.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/constants/GeoConstants.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/constants/TelemetryConstants.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/http/GzipRequestInterceptor.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/http/TelemetryClient.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/location/AndroidLocationEngine.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/location/LocationEngine.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/location/TelemetryLocationReceiver.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/permissions/PermissionsManager.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/service/TelemetryService.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/utils/MathUtils.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/utils/TelemetryUtils.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/MapboxDirections.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/mapmatching/v4/models/MapMatchingResponse.java
Extracted from the main SDK and refactored for a more loosely coupled architecture. Please note this is still a WIP.
/cc: @mapbox/android
> Telemetry module

- mapbox/app/build.gradle
- mapbox/app/src/main/java/com/mapbox/services/android/testapp/directions/DirectionsV5Activity.java
- mapbox/dependencies.gradle
- mapbox/libjava-services-rx/build.gradle
- mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/directions/v5/DirectionsServiceRx.java
- mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/directions/v5/MapboxDirectionsRx.java
- mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/distance/v1/DistanceServiceRx.java
- mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/distance/v1/MapboxDistanceRx.java
- mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/geocoding/v5/GeocodingServiceRx.java
- mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/geocoding/v5/MapboxGeocodingRx.java
- mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/mapmatching/v4/MapMatchingServiceRx.java
- mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/mapmatching/v4/MapboxMapMatchingRx.java
- mapbox/libjava-services-rx/src/test/java/com/mapbox/services/api/rx/directions/v5/MapboxDirectionsRxTest.java
- mapbox/libjava-services-rx/src/test/java/com/mapbox/services/api/rx/distance/v1/MapboxDistanceRxTest.java
- mapbox/libjava-services-rx/src/test/java/com/mapbox/services/api/rx/geocoding/v5/MapboxGeocodingRxTest.java
- mapbox/libjava-services-rx/src/test/java/com/mapbox/services/api/rx/mapmatching/v4/MapboxMapMatchingRxTest.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/MapboxDirections.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/distance/v1/DistanceService.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/distance/v1/MapboxDistance.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/geocoding/v5/GeocodingService.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/geocoding/v5/MapboxGeocoding.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/mapmatching/v4/MapMatchingService.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/mapmatching/v4/MapboxMapMatching.java
WIP to bring back support for Rx as part of the `libjava-services-rx` module.
The first stab at it, extending the current `MapboxDirections` class, works but brings an inconsistent API. Unlike with the normal client where the `Builder` brings the `MapboxDirections` instance. Right now, we need to use them separately as we cannot use the `build` method:
```
MapboxDirectionsRx.Builder builder = new MapboxDirectionsRx.Builder()
.setAccessToken(Utils.getMapboxAccessToken(this))
.setCoordinates(positions)
.setProfile(DirectionsCriteria.PROFILE_DRIVING)
.setSteps(true)
.setOverview(DirectionsCriteria.OVERVIEW_FULL);
MapboxDirectionsRx clientRx = new MapboxDirectionsRx(builder);
clientRx.getObservable()
.subscribeOn(Schedulers.newThread())
.observeOn(AndroidSchedulers.mainThread()) …
```
> RxJava support

- mapbox/app/src/main/java/com/mapbox/services/android/testapp/MainActivity.java
- mapbox/libjava-core/src/main/java/com/mapbox/services/Constants.java
- mapbox/libjava-core/src/main/java/com/mapbox/services/commons/models/Position.java
This PR does two things:
- Adds a new `Position.fromLngLat(double longitude, double latitude)` method the be more explicit about the lat/lon order. It does not deprecate the `Position.fromCoordinates()` method as this is used for other cases too (e.g. set an altitude or a double array). Fixes https://github.com/mapbox/mapbox-java/issues/283.
- Adds a warning to the `Position` constructor if the lat/lon values seem out of range. Fixes https://github.com/mapbox/mapbox-java/issues/266.
This last item is tested via the Test App. In `MainActivity` we create an object with values out of range and the warning can be seen as usual in the Android log window:
@cammace Please review.
> Conveniences to Position model

- Makefile
- mapbox/libjava-core/src/main/java/com/mapbox/services/Constants.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/DirectionsCriteria.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/MapboxDirections.java
- mapbox/libjava-services/src/test/fixtures/directions_v5_precision_6.json
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/directions/v5/MapboxDirectionsTest.java
Closes #207 
Closes #288
Bring over the work done in #228 and completes it.
> Adds support for polyline6

- scripts/release.py
The script is [based on the SDK version](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/scripts/release.py), but adapted for MAS where a few steps don't apply.
Usage is however equivalent:
```
$ python release.py --help
Usage: release.py [OPTIONS]
Options:
--stage [snapshot|beta|final]  The release stage.
--version TEXT                 The version you want to publish. E.g:
2.0.0-SNAPSHOT, 2.0.0-beta.1, or 2.0.0. If
you set the version to "current", the script
will default to the current SNAPSHOT version.
--help                         Show this message and exit.
```
Examples:
- Publish a snapshot from master (release.py uses the current branch)
```
$ git branch
* master
1234-fix-crash
$ python release.py --stage snapshot
```
- Publish a snapshot from a feature …
> Introduce the release.py script for MAS

- CHANGELOG.md
- mapbox/app/src/main/java/com/mapbox/services/android/testapp/directions/DirectionsV5Activity.java
- mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/directions/v5/DirectionsServiceRx.java
- mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/directions/v5/MapboxDirectionsRx.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/DirectionsService.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/MapboxDirections.java
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/directions/v5/MapboxDirectionsTest.java
We were missing this parameter in our builder.
> Added bearing query parameter 

- mapbox/libjava-services/src/main/java/com/mapbox/services/api/MapboxService.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/MapboxDirections.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/distance/v1/MapboxDistance.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/geocoding/v5/MapboxGeocoding.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/mapmatching/v5/MapboxMapMatching.java
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/directions/v5/MapboxDirectionsTest.java
Fixes https://github.com/mapbox/mapbox-java/issues/343.
> Expose okhttp3.Call.Factory in all services

- mapbox/libandroid-services/build.gradle
- mapbox/libandroid-services/src/main/java/com/mapbox/services/android/Constants.java
- mapbox/libandroid-services/src/main/java/com/mapbox/services/android/navigation/v5/AlertLevelChangeListener.java
- mapbox/libandroid-services/src/main/java/com/mapbox/services/android/navigation/v5/LocationUpdatedThread.java
- mapbox/libandroid-services/src/main/java/com/mapbox/services/android/navigation/v5/MapboxNavigation.java
- mapbox/libandroid-services/src/main/java/com/mapbox/services/android/navigation/v5/NavigationEventListener.java
- mapbox/libandroid-services/src/main/java/com/mapbox/services/android/navigation/v5/NavigationService.java
- mapbox/libandroid-services/src/main/java/com/mapbox/services/android/navigation/v5/ProgressChangeListener.java
- mapbox/libandroid-services/src/main/res/drawable/ic_navigation_black.xml
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/utils/MathUtils.java
- mapbox/libjava-core/src/main/java/com/mapbox/services/Experimental.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/navigation/v5/RouteProgress.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/navigation/v5/RouteUtils.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/utils/turf/TurfMeta.java
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/navigation/v5/RouteUtilsTest.java
This PR brings the navigation logic authored by @cammace into MAS.
It also introduces a new `Experimental` annotation. These APIs are evolving quickly over the next few versions and SEMVER won't be necessarily guaranteed.
cc: @cammace
> Navigation SDK for Android

- mapbox/libjava-services/src/main/java/com/mapbox/services/api/MapboxService.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/MapboxDirections.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/DirectionsResponse.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/DirectionsRoute.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/DirectionsWaypoint.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/IntersectionLanes.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/LegStep.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/RouteLeg.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/StepIntersection.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/StepManeuver.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/distance/v1/MapboxDistance.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/geocoding/v5/MapboxGeocoding.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/geocoding/v5/models/CarmenContext.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/geocoding/v5/models/CarmenFeatureCollection.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/mapmatching/v5/MapboxMapMatching.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/mapmatching/v5/models/MapMatchingMatching.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/mapmatching/v5/models/MapMatchingResponse.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/mapmatching/v5/models/MapMatchingTracepoint.java
Turns out that the approach in https://github.com/mapbox/mapbox-java/pull/344 wouldn't work if both the client and the factory were set at the same time. This PR makes sure we only set one.
It also adds a number of no-args constructors to make Gson happy.
> AppEngine support (and II)

- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/connectivity/ConnectivityReceiver.java
This PR allows to use ConnectivityReceiver with multiple components. Underneath it uses an activation counter to determine if we still need keep the broadcast events around when calling `removeConnectivityUpdates` or to determine is we need to start listening to connectivity changes when we call `requestConnectivityUpdates`. I have annotated the mentioned methods with `@UIThread` to avoid thread unsafe access to the activation counter.
> Multiple components setup for ConnectivityReceiver

- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/TelemetryLocationReceiver.java
Fixes https://github.com/mapbox/mapbox-java/issues/389.
It also removes unnecessary logging from `TelemetryLocationReceiver` (the `TelemetryListener` should be used instead to hook up to location updates).
> Remove all elements after a failed request

- mapbox/libandroid-services/src/main/java/com/mapbox/services/android/location/LostLocationEngine.java
With the upgrade from LOST 1.0.0 to 2.0.0, it seems to be required to add an interval to the location request. This is shown in the documentation [here](https://github.com/mapzen/lost/blob/master/docs/location-updates.md) though it's not mentioned in the [upgrade guide](https://github.com/mapzen/lost/blob/master/docs/upgrade-1x-2.md) from v1 -> v2.
Closes #392
> LostLocationEngine - add interval to request

- mapbox/libandroid-services/src/main/java/com/mapbox/services/android/location/LostLocationEngine.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/location/LocationEngine.java
> added setters to location engine and javadoc

- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/MapboxDirections.java
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/directions/v5/MapboxDirectionsTest.java
closes: #378
replaces PR https://github.com/mapbox/mapbox-java/pull/383
you are allowed to set only origin and destination or origin, destination, and a list of coordinates. if a list is provided, it will go in between the origin and destination when creating the string for the API.
> Adds fix for origin and destination overriding list

- Makefile
- mapbox/gradle-mvn-push-android.gradle
- mapbox/gradle-mvn-push-java.gradle
- mapbox/gradle.properties
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxEvent.java
In order to build locally (same procedure to both Android and Java libraries):
1. Set `IS_LOCAL_DEVELOPMENT` gradle property to `true` (is `false` by default)
2. `$> gradlew uploadArchives`
3. `aar` or `jar` will be automatically installed in your Maven local repo folder (`.m2`/`M2_HOME`)
4. Remember to add `mavenLocal()` in `repositories{}` (`build.gradle`) in the project in which you'd like to use Maven local repository
👀  @zugaldia
> Add local aar and jar generation support

- mapbox/libjava-core/src/main/java/com/mapbox/services/commons/models/Position.java
- mapbox/libjava-core/src/main/java/com/mapbox/services/commons/utils/TextUtils.java
- mapbox/libjava-geojson/src/test/java/com/mapbox/services/commons/geojson/FeatureCollectionTest.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/MapboxDirections.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/geocoding/v5/MapboxGeocoding.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/mapmatching/v5/MapboxMapMatching.java
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/directions/v5/MapboxDirectionsTest.java
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/geocoding/v5/MapboxGeocodingTest.java
closes https://github.com/mapbox/mapbox-java/issues/338
> Remove trailing zeros from coordinates

- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/models/LegAnnotation.java
The speed is measured in meters per second, not kilometers per hour.
/cc @cammace @miccolis
> Document correct units for LegAnnotation.speed

- mapbox/libjava-services/src/main/java/com/mapbox/services/api/utils/turf/TurfConstants.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/utils/turf/TurfHelpers.java
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/turf/TurfHelpersTest.java
Adds the convertDistance method https://github.com/Turfjs/turf/blob/master/packages/turf-helpers/index.js#L396. It also adds support for centimeters and feet.
cc: @zugaldia
> added convert distance method to TurfHelper

- mapbox/libjava-services/src/main/java/com/mapbox/services/api/staticimage/v1/models/StaticMarkerAnnotation.java
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/staticimage/v1/StaticMarkerAnnotationTest.java
Fixes [mapbox/mapbox-gl-native#9107](https://github.com/mapbox/mapbox-gl-native/issues/9107)
👀 @zugaldia @cammace
> Fix static marker annotation url generation

- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/MapboxDirections.java
`PROFILE_DRIVING_TRAFFIC` has a much lower limit of only three waypoints, per [the API documentation](https://www.mapbox.com/api-documentation/#directions).
/ref mapbox/MapboxDirections.swift#142
/cc @cammace @danswick
> Clarify waypoint limit

- mapbox/app/build.gradle
- mapbox/app/src/main/java/com/mapbox/services/android/testapp/location/GoogleLocationEngine.java
- mapbox/app/src/main/java/com/mapbox/services/android/testapp/location/LocationEngineActivity.java
- mapbox/dependencies.gradle
- mapbox/libandroid-services/build.gradle
- mapbox/libandroid-services/src/main/java/com/mapbox/services/android/location/LostLocationEngine.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/location/AndroidLocationEngine.java
- scripts/bitrise.yml
Copied from downstream ticket in https://github.com/mapbox/mapbox-gl-native/pull/9394:
> We have been having some issues with recent releases of the LOST library. To be able to ship a next final release for 5.1.0. We are downgrading back to `v1.1.1`. This version shipped as part of our 4.x series.
This PR requires a newer version of the SDK first to pass CI, excluding lost from the maps sdk makes the test application crash at startup.
> downgrade LOST to v1.1.1

- mapbox/libandroid-services/src/main/java/com/mapbox/services/android/location/MockLocationEngine.java
Wasn't increasing indexes correctly, this PR fixes that and tries to also improve the logic slightly so there isn't as much lag between steps.
> support for multiple legs

- Makefile
- mapbox/build.gradle
- mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/directions/v5/DirectionsServiceRx.java
- mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/directions/v5/MapboxDirectionsRx.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/DirectionsService.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directions/v5/MapboxDirections.java
- mapbox/libjava-services/src/test/fixtures/directions_annotations_v5.json
- mapbox/libjava-services/src/test/fixtures/directions_v5.json
- mapbox/libjava-services/src/test/fixtures/directions_v5_precision_6.json
- mapbox/libjava-services/src/test/fixtures/directions_v5_traffic.json
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/directions/v5/MapboxDirectionsTest.java
Closes https://github.com/mapbox/mapbox-java/issues/474
Adds support for the language param in the directions API. Also updated the fixtures for directions to ensure everything's still working properly.
> Added directions support for languages

- Makefile
- mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/mapmatching/v5/MapMatchingServiceRx.java
- mapbox/libjava-services-rx/src/main/java/com/mapbox/services/api/rx/mapmatching/v5/MapboxMapMatchingRx.java
- mapbox/libjava-services-rx/src/test/java/com/mapbox/services/api/rx/BaseTest.java
- mapbox/libjava-services-rx/src/test/java/com/mapbox/services/api/rx/mapmatching/v5/MapboxMapMatchingRxTest.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/mapmatching/v5/MapMatchingService.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/mapmatching/v5/MapboxMapMatching.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/mapmatching/v5/models/MapMatchingTracepoint.java
- mapbox/libjava-services/src/test/fixtures/mapmatching_v5_polyline.json
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/BaseTest.java
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/mapmatching/v5/MapboxMapMatchingTest.java
This PR fixes up the map matching api:
- Adds `alternatives_count` to MapMatchingTraceoint class
- Adds support for the language param
> Fixed up mapmatching API

- mapbox/libjava-geojson/src/main/java/com/mapbox/services/commons/geojson/Point.java
- mapbox/libjava-services/src/main/java/com/mapbox/services/api/utils/turf/TurfMisc.java
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/turf/TurfMeasurementTest.java
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/turf/TurfMiscTest.java
> added test and exception if null point exist during operations

- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
A user reported seeing time spend on reflection when profiling:
> `MapboxTelemetry.class.getSimpleName();`
Replacing with a fixed String solves this.
> MapboxTelemetry String Log tag

- mapbox/app/proguard-rules.pro
- mapbox/libandroid-services/proguard-rules.pro
Rules to enforce keeping model classes for the new APIs. I ran into one issue but seems to be related to the Map SDK and its Proguard rules (opened a ticket https://github.com/mapbox/mapbox-gl-native/issues/9569)
> added some new Proguard rules

- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/http/TelemetryClient.java
This API lets us manually control the verbosity of HTTP requests.
> Introduce setDebugLoggingEnabled API

- INSTALL.md
- README.md
In order to fix https://github.com/mapbox/mapbox-java/issues/559, I edited the content of INSTALL.md and README.md to clarify that mapbox-java/mapbox folder should be imported as a root project folder in Android Studio
cc: @zugaldia
> Unclear setup instruction

- mapbox/app/src/main/res/values/strings.xml
Marked the `default_style` string as being untranslatable so translators on Transifex don’t feel pressured to translate it to some other value like `mapbox://estilos/mapbox/caminos-v9`.
/cc @cammace @langsmith
> Mark style URL as untranslatable

- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
- Adds `newUserAgent(String userAgent)`
👀 @cammace @ericrwolfe @zugaldia
> Introduce new user agent API

- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxEvent.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
- Adds missing `device` attribute to Navigation events
👀 @cammace @ericrwolfe @zugaldia
> Add missing device attribute to Navigation events

- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/navigation/MapboxNavigationEvent.java
- `originalRequestIdentifier`, `requestIdentifier` and `audioType` used in [`NavigationMetricsWrapper`](https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationMetricsWrapper.java) (Nav SDK) may be `"null"` so this PR:
- Omits `originalRequestIdentifier`, `requestIdentifier` and `audioType` optional fields (when `"null"`) over sending `null`s
👀 @cammace @ericrwolfe @zugaldia
> Omit null optional fields in Nav events

- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/location/GoogleLocationEngine.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/location/LostLocationEngine.java
- Fix location engines activation calling `onConnected` method if the location engine was already connected
👀 @zugaldia @electrostat @cammace
> Fix location engines activation

- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/navigation/MapboxNavigationEvent.java
Allow events to handle Null parameters and prevent crashes
Issue: [Issue #583](https://github.com/mapbox/mapbox-java/issues/583)
> Telemetry events handle null parameters

- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/navigation/MapboxNavigationEvent.java
Closes #585
Current iteration returns a string instead of a json object.
> Step Metadata is serialized improperly

- mapbox/libjava-services/src/main/java/com/mapbox/services/api/directionsmatrix/v1/MapboxDirectionsMatrix.java
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/directionsmatrix/v1/MapboxDirectionsMatrixTest.java
Fixed getDestinations and getSources return values from MapboxDirectionsMatrix.Builder.
Fixes #579.
> Fixed source and destination formatting from DirectionsMatrix request builder

- mapbox/libandroid-services/build.gradle
- mapbox/libandroid-services/src/main/java/com/mapbox/services/android/location/LostLocationEngine.java
LOST is added as a dependency again inside libandroid-services and the LOST location provider is duplicated back into it's original package but deprecated now.
> placed things back to their original location to not break API

- mapbox/app/build.gradle
- mapbox/dependencies.gradle
- mapbox/libandroid-services/build.gradle
- mapbox/libandroid-services/src/main/java/com/mapbox/services/android/location/LostLocationEngine.java
- mapbox/libandroid-telemetry/build.gradle
- Makes lost dependency `provided`
- Per Lost 3.x excluding `guava` is not needed anymore
👀 @cammace @zugaldia
> Make lost dependency provided

- circle.yml
- mapbox/app/build.gradle
- mapbox/libandroid-services/src/main/java/com/mapbox/services/android/location/LostLocationEngine.java
- mapbox/libandroid-telemetry/build.gradle
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/location/LostLocationEngine.java
Building a SNAPSHOT from this branch to test if things are working in navigation properly before merging.
> Reverted lost to 1.1

- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
Issue found when testing on YotaPhone. BatteryStatus can be null and throws a Null Pointer Exception.
cc @lilykaiser
> NPE for BatteryStatus

- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/http/TelemetryClient.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/navigation/MapboxNavigationEvent.java
- Adds telem `absoluteDistanceToDestination` track support
👀 @electrostat @danesfeder @ericrwolfe @zugaldia
> Add telem absolute distance to destination support

- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/http/TelemetryClient.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/navigation/MapboxNavigationEvent.java
- Adds telem `percentTimeInForeground` and `percentTimeInPortrait` track support
👀 @zugaldia @danesfeder @electrostat @ericrwolfe
> Add telem percent time in foreground and in portrait track support

- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/navigation/MapboxNavigationEvent.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/utils/AudioTypeChain.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/utils/AudioTypeResolver.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/utils/BluetoothAudioType.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/utils/HeadphonesAudioType.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/utils/SpeakerAudioType.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/utils/TelemetryUtils.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/utils/UnknownAudioType.java
- Adds telem `audioType` support using a chain of responsibility:
`speaker` > `bluetooth` > `headphones` > `unknown`
👀 @zugaldia @cammace @electrostat @ericrwolfe
> Add telem audio type support

- mapbox/app/build.gradle
- mapbox/dependencies.gradle
- mapbox/libandroid-services/build.gradle
- mapbox/libandroid-services/src/main/java/com/mapbox/services/android/location/LostLocationEngine.java
- mapbox/libandroid-telemetry/build.gradle
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/location/LostLocationEngine.java
- Bumps Lost version to `3.0.4`
Needed to solve https://github.com/mapbox/mapbox-gl-native/issues/9581
👀 @zugaldia @tobrun @cammace
> Bump Lost version to 3.0.4

- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/location/LocationEngine.java
- Adds `LocationEngine#obtainType()` javadoc
👀 @osana
> Add obtain location engine type javadoc

- circle.yml
PR bumping the used CI docker images to mbgl/ci:20171122150543-android-ndk-r16.
> bump ci image

- gradle/dependencies.gradle
We recently had some [issues](https://github.com/mapbox/mapbox-gl-native/pull/10366) with OkHttp in gl-native (see [changelog](https://github.com/square/okhttp/blob/master/CHANGELOG.md) of patches included for 3.9.1).
Since these fixes are significant, I went ahead and created this PR. I added this to 3.0.0 for now, but feel free to remove or alter.
> Bump OkHttp and retrofit versions

- services-directions/src/main/java/com/mapbox/directions/v5/MapboxDirections.java
- services-directions/src/main/java/com/mapbox/directions/v5/models/RouteOptions.java
> Save access token and request uuid in route options

- services-core/src/main/java/com/mapbox/core/internal/Preconditions.java
- services-turf/src/main/java/com/mapbox/turf/TurfMeasurement.java
- services-turf/src/main/java/com/mapbox/turf/TurfMisc.java
- services-turf/src/test/java/com/mapbox/turf/TurfMiscTest.java
I've also added a `checkNotNull` so we can use it throughout the SDKs.
> add check and test for pointOnLine list less than 2

- services-geojson/src/main/java/com/mapbox/geojson/utils/PolylineUtils.java
- services-geojson/src/test/java/com/mapbox/geojson/utils/PolylineUtilsTest.java
Closes https://github.com/mapbox/mapbox-java/issues/633
Even with an empty list or path string, the returned results for all PolylineUtils results in a nonnull value, thus annotating the methods will help developers know they can skip over this check.
> Adds annotations and test for polylineUtils

- samples/build.gradle
- samples/src/main/java/com/mapbox/samples/BasicDirections.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
> Cleaned up routeOptions class

- LICENSE
This doc was missing in master, re-adding it from the 2.x branch.
> Add license back from 2.x branch

- .gitignore
- Makefile
in the projects root folder, run `make javadoc` this will generate the javadoc and place all the project documentation inside a `documentation` folder at the projects root.
> Simplify javadoc creation in project

- circle.yml
- mapbox/dependencies.gradle
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/MapboxTelemetry.java
- mapbox/libandroid-telemetry/src/main/java/com/mapbox/services/android/telemetry/utils/TelemetryUtils.java
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/directions/v5/MapboxDirectionsTest.java
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/geocoding/v5/MapboxGeocodingTest.java
- mapbox/libjava-services/src/test/java/com/mapbox/services/api/optimizedtrips/v1/MapboxOptimizedTripsTest.java
In OkHttp 3.10.0, `toHumanReadableAscii` util method has been moved to `OkHttpURLConnection` and marked as private. Since we previously relied on this method, I've ported over the same method into our utils class.
> moved toHumanReadableAscii method into library

- circle.yml
- mapbox/app/build.gradle
- mapbox/build.gradle
- mapbox/dependencies.gradle
- mapbox/gradle/wrapper/gradle-wrapper.properties
- mapbox/libandroid-services/build.gradle
- mapbox/libandroid-services/gradle-javadoc.gradle
- mapbox/libandroid-telemetry/build.gradle
- mapbox/libandroid-ui/build.gradle
- mapbox/libandroid-ui/gradle-javadoc.gradle
- mapbox/libjava-core/build.gradle
- mapbox/libjava-geojson/build.gradle
- mapbox/libjava-services-rx/build.gradle
- mapbox/libjava-services/build.gradle
- Updates MAS 2.x.x to Gradle 4.1 and Gradle tools 3.0
Needed to fix https://github.com/mapbox/mapbox-gl-native/issues/11125
👀 @LukasPaczos @tobrun @zugaldia @lilykaiser
> Update Gradle in MAS 2.x.x

- README.md
This pr adjust this repo's README to remove mention of Mapbox _Android_ Services. Switches to Mapbox Java Services
> Update mentions of MAS to Mapbox Java Services

- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
In the navigation SDK, we need the baseUrl in `RouteOptions` to ensure our re-routing requests go to the same endpoint as the original route.
> Add baseUrl to RouteOptions

- samples/build.gradle
- services-core/build.gradle
- services-directions/build.gradle
- services-geocoding/build.gradle
- services-geojson/build.gradle
- services-matching/build.gradle
- services-matrix/build.gradle
- services-optimization/build.gradle
- services-staticmap/build.gradle
- services-turf/build.gradle
- services/build.gradle
This PR merges into https://github.com/mapbox/mapbox-java/pull/737 and reworks the dependency tree.
> Rework dependency tree, use api instead of implementation

- services-directions/src/main/java/com/mapbox/api/directions/v5/models/BannerText.java
Add `degrees` and `driving_side` to the `BannerText` object. 
Degrees will be used to create specific roundabout icons for the given displayed roundabout in the instruction banner. 
cc @allierowan @lyzidiamond for extra 👀
> Add Degrees and Driving Side to BannerText

- services-geocoding/src/test/java/com/mapbox/api/geocoding/v5/models/CarmenFeatureTest.java
- services-geojson/src/main/java/com/mapbox/geojson/CoordinateContainer.java
- services-geojson/src/main/java/com/mapbox/geojson/Geometry.java
- services-geojson/src/main/java/com/mapbox/geojson/GeometryCollection.java
- services-geojson/src/main/java/com/mapbox/geojson/LineString.java
- services-geojson/src/main/java/com/mapbox/geojson/MultiLineString.java
- services-geojson/src/main/java/com/mapbox/geojson/MultiPoint.java
- services-geojson/src/main/java/com/mapbox/geojson/MultiPolygon.java
- services-geojson/src/main/java/com/mapbox/geojson/Point.java
- services-geojson/src/main/java/com/mapbox/geojson/Polygon.java
- services-geojson/src/main/java/com/mapbox/geojson/gson/GeometryTypeAdapter.java
> Make GeometryCollection a Geometry

- services-core/src/main/java/com/mapbox/core/utils/ApiCallHelper.java
- services-core/src/test/java/com/mapbox/core/utils/ApiCallHelperTest.java
> remove unprintable chars

- samples/build.gradle
- services-core/build.gradle
- services-directions/build.gradle
- services-geocoding/build.gradle
- services-geojson/build.gradle
- services-matching/build.gradle
- services-matrix/build.gradle
- services-optimization/build.gradle
- services-staticmap/build.gradle
- services-turf/build.gradle
- services/build.gradle
> changed compile into implemenation

- services-directions/src/main/java/com/mapbox/api/directions/v5/models/BannerComponents.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/BannerComponentTest.java
Added recently for banner instruction work to be consumed by the navigation SDK.
cc @devotaaabel @Guardiola31337
> Add Abbreviations and type to BannerComponent

- services-matching/src/main/java/com/mapbox/api/matching/v5/MapMatchingService.java
- services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java
- services-matching/src/test/java/com/mapbox/api/matching/v5/MapboxMapMatchingTest.java
Adds voice units param to map matching request to be used to configure the voice instructions provided by the API
> Add voiceUnits to MapMatching

- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
- services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java
- services-matching/src/test/java/com/mapbox/api/matching/v5/MapboxMapMatchingTest.java
closes #763 
Make sure request and headers are not erased
when response is tweaked to inlculde routeOptions
> Make sure request and headers are not erased

- services-directions/src/main/java/com/mapbox/api/directions/v5/DirectionsCriteria.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/LegAnnotation.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/MaxSpeed.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/MaxSpeedTest.java
> Add MaxSpeed Annotation to Directions API

- README.md
Part of the 3.0.0 Mapbox Java SDK release: https://github.com/mapbox/mapbox-java/issues/774
> Bumped snapshot to 3.1.0 in repo readme

- services-geojson/src/main/java/com/mapbox/geojson/BoundingBox.java
- services-geojson/src/main/java/com/mapbox/geojson/gson/BoundingBoxDeserializer.java
- services-geojson/src/test/java/com/mapbox/geojson/FeatureCollectionTest.java
- services-geojson/src/test/java/com/mapbox/geojson/FeatureTest.java
- services-geojson/src/test/java/com/mapbox/geojson/GeometryCollectionTest.java
- services-geojson/src/test/java/com/mapbox/geojson/LineStringTest.java
- services-geojson/src/test/java/com/mapbox/geojson/MultiLineStringTest.java
- services-geojson/src/test/java/com/mapbox/geojson/MultiPointTest.java
- services-geojson/src/test/java/com/mapbox/geojson/MultiPolygonTest.java
- services-geojson/src/test/java/com/mapbox/geojson/PointTest.java
- services-geojson/src/test/java/com/mapbox/geojson/PolygonTest.java
- services-staticmap/src/test/java/com/mapbox/api/staticmap/v1/models/StaticMarkerAnnotationTest.java
rename BoundingBox.fromCoordinates() to BoundingBox.fromLngLats() 
for consistency with the rest of the API
closes #788
> rename BoundingBox.fromCoordinates() to BoundingBox.fromLngLats() 

- services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/MapboxGeocoding.java
Does what the title says - the link was pointing to the wrong area for the java-sdk Android docs.
> Fix broken geocoding docs link

- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
- services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java
- services-matching/src/test/java/com/mapbox/api/matching/v5/MapboxMapMatchingTest.java
Adds approaches to `RouteOptions` after a successful response has been received by either the Directions or Map Matching API.
> Add approaches to RouteOptions

- services-directions/src/main/java/com/mapbox/api/directions/v5/models/BannerComponents.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/BannerInstructions.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/BannerText.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsJsonObject.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsResponse.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsRoute.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsWaypoint.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/IntersectionLanes.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/LegAnnotation.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/LegStep.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/MaxSpeed.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/RouteLeg.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/StepIntersection.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/StepManeuver.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/VoiceInstructions.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/BannerComponentTest.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/BannerInstructionsTest.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/BannerTextTest.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/DirectionsResponseTest.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/DirectionsWaypointTest.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/IntersectionLanesTest.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/LegAnnotationTest.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/LegStepTest.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/MaxSpeedTest.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/RouteLegTest.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/StepIntersectionTest.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/StepManeuverTest.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/VoiceInstructionsTest.java
> added toJson and fromJson to Directions models

- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
- services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/MapboxGeocoding.java
- services-geocoding/src/test/java/com/mapbox/api/geocoding/v5/MapboxGeocodingTest.java
- services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java
- services-matching/src/test/java/com/mapbox/api/matching/v5/MapboxMapMatchingTest.java
- services-matrix/src/test/java/com/mapbox/api/matrix/v1/MapboxMatrixTest.java
- services-optimization/src/main/java/com/mapbox/api/optimization/v1/MapboxOptimization.java
- services-optimization/src/test/java/com/mapbox/api/optimization/v1/MapboxOptimizationTest.java
- services-staticmap/src/main/java/com/mapbox/api/staticmap/v1/MapboxStaticMap.java
- services-staticmap/src/test/java/com/mapbox/api/staticmap/v1/MapboxStaticMapTest.java
> all accesToken fields should be annotated with @NonNull

- services-geojson/src/main/java/com/mapbox/geojson/Feature.java
- services-geojson/src/main/java/com/mapbox/geojson/MultiPoint.java
- services-geojson/src/main/java/com/mapbox/geojson/Polygon.java
- services-geojson/src/test/java/com/mapbox/geojson/LineStringTest.java
- services-geojson/src/test/java/com/mapbox/geojson/MultiLineStringTest.java
- services-geojson/src/test/java/com/mapbox/geojson/MultiPointTest.java
- services-geojson/src/test/java/com/mapbox/geojson/MultiPolygonTest.java
- services-geojson/src/test/java/com/mapbox/geojson/PointTest.java
- services-geojson/src/test/java/com/mapbox/geojson/PolygonTest.java
coordinates() should have @NotNull annotation in Geometry implementations
closes #881 
addresses #880
> coordinates() should have @NotNull annotation in Geometry implementations

- build.gradle
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/RouteLegTest.java
- services-geojson/src/main/java/com/mapbox/geojson/Geometry.java
- services-geojson/src/main/java/com/mapbox/geojson/gson/GeometryGeoJson.java
- services-geojson/src/test/java/com/mapbox/geojson/GeometryTest.java
closes #868 
related to #832
java8 was introduced by #770 #749
>  java 7 downgrade

- services-directions/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
closes #894 
RouteOptions.test_toJson test is still failing com.google.gson.stream.MalformedJsonException
@Guardiola31337  There must be some typo... that I cannot see. Could you 👀 .
> Route options should be serialized/deserialized using backend names

- .github/stale.yml
Enable a bot that will automatically archive issues older than 6 months or PR older than 2 months.
The bot will run every our and will archive one single issue per hour.
Archived issues will be labeled as "archived" and can be reopened if needed. Commenting on the issue or PR or simply updating the PR branch is enough to count as "activity" and reset the stale counter.
> Archive stale issues and pull request

- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java
> Remove dependency on BindingContextFactory

- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
- Remove waypoint limit check - there is no such a limitation for offline routes (`MapboxDirections` is used to generate offline routes URLs). For online, we're still accounting for that because the Directions API will throw an error which is handled gracefully by `MapboxDirections`.
cc @osana
> Remove waypoint limit check

- services-geojson/src/main/java/com/mapbox/geojson/gson/BoundingBoxSerializer.java
- services-geojson/src/main/java/com/mapbox/geojson/gson/CoordinateTypeAdapter.java
- services-geojson/src/main/java/com/mapbox/geojson/gson/PointSerializer.java
- services-geojson/src/main/java/com/mapbox/geojson/utils/GeoJsonUtils.java
- services-geojson/src/test/java/com/mapbox/geojson/utils/GeoJsonUtilsTest.java
> to improve performance: do not use BigDecimal for rounding

- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
- services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java
- services-matching/src/test/java/com/mapbox/api/matching/v5/MapboxMapMatchingTest.java
- Removes character waypoint names limit from `MapboxMapMatching` and `MapboxDirections`
Refs. https://github.com/mapbox/mapbox-java/pull/940#pullrequestreview-185610135
This PR removes the hard-coded check for a max of 500 characters total for all waypoint names in `MapboxMapMatching` and `MapboxDirections` 👀 https://github.com/mapbox/api-directions/pull/1625
We shouldn't enforce this in the java code - the error code / message will still be returned from the server.
cc @danpaz @danpat
> Remove character waypoint names limit from MapboxMapMatching and MapboxDirections

- README.md
Very confusingly, this repo's README still shows `2.2.10` as the latest version of various Java services. It's actually `4.3.0`. This is because the badge was still referencing `mapbox-android-services` in its url. This pr fixes the Maven Central link URL so that the correct # appears.
**Before:**
**After:**
> Fix README's maven central badge

- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
In order to gain more insight to network calls happening in `MapboxDirections`, we can add the `Interceptor` and `EventListener` components to the `MapboxDirections` builder.
> Add Interceptor and EventListener to MapboxDirections

- services-directions/src/main/java/com/mapbox/api/directions/v5/DirectionsService.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
Fixes #956 
- Adds via waypoints support to `MapboxDirections`
> Add via waypoints support to MapboxDirections

- services-directions/src/main/java/com/mapbox/api/directions/v5/DirectionsService.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
- Follow up from https://github.com/mapbox/mapbox-java/pull/959
We found in https://github.com/mapbox/mapbox-navigation-android/pull/1733#discussion_r255541722 that naming could be confusing and should be more explicit in order to make clients' life easier.
> Fix via waypoints APIs naming

- services-directions/src/main/java/com/mapbox/api/directions/v5/DirectionsService.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
- services-matching/src/main/java/com/mapbox/api/matching/v5/MapMatchingService.java
- services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java
- services-matching/src/test/java/com/mapbox/api/matching/v5/MapboxMapMatchingTest.java
Follow up PR from latest feedback in https://github.com/mapbox/mapbox-java/pull/961
Edited:
- Fix waypoints APIs naming for map matching and directions services - from `waypoints` to ~`separatesLegs`~ waypoint indices 👀 https://github.com/mapbox/mapbox-java/pull/962#issuecomment-462809409
Noting that for the Map Matching service we're deprecating https://github.com/mapbox/mapbox-java/blob/c834c07361e8b6283b93b098930413a06e933c64/services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java#L488 in favor of https://github.com/mapbox/mapbox-java/blob/aba088c98a2bab20c155667eab8d447275cb03e2/services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java#L507 to avoid breaking SemVer.
cc @1ec5
> Fix waypoints APIs naming for map matching and directions services

- services-route-tiles/src/main/java/com/mapbox/api/routetiles/v1/MapboxRouteTiles.java
Closes #974 
This is needed to unblock calculating the progress of tile downloads in the Navigation SDK.
cc @akitchen
> Add Interceptor support for MapboxRouteTiles

- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
This PR adds the ability to the `MapboxDirections` API to choose the appropriate http method (get vs. post) based on the length of the url. If the `get` url is longer than `8 * 1024` characters, then it uses post. The developer can still specify a specific method to use if they would like, and that will override this behavior.
> Added automatic choosing of POST method when a method is not specified and the url for a get call is longer than 1024*8

- services-core/src/main/java/com/mapbox/core/MapboxService.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java
- services-matching/src/test/java/com/mapbox/api/matching/v5/MapboxMapMatchingTest.java
Updated map matching to use same logic as the directions API to automatically use a post request when the size of the url exceeds the maximum for a get request.
> Updated map matching to use a POST request if the url for a GET request is larger than the maximum allowed size

- services-core/build.gradle
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/LegStep.java
- services-geojson/build.gradle
- services-geojson/src/test/java/com/mapbox/geojson/LineStringTest.java
- services-geojson/src/test/java/com/mapbox/geojson/MultiLineStringTest.java
- services-geojson/src/test/java/com/mapbox/geojson/TestUtils.java
- services-geojson/src/test/java/com/mapbox/geojson/utils/PolylineUtilsTest.java
- services-turf/build.gradle
- services-turf/src/main/java/com/mapbox/turf/TurfAssertions.java
- services-turf/src/main/java/com/mapbox/turf/TurfMisc.java
- services-turf/src/main/java/com/mapbox/turf/models/LineIntersectsResult.java
- services-turf/src/test/java/com/mapbox/turf/TestUtils.java
- services-turf/src/test/java/com/mapbox/turf/TurfAssertionsTest.java
- services-turf/src/test/java/com/mapbox/turf/TurfClassificationTest.java
- services-turf/src/test/java/com/mapbox/turf/TurfConversionTest.java
- services-turf/src/test/java/com/mapbox/turf/TurfJoinsTest.java
- services-turf/src/test/java/com/mapbox/turf/TurfMeasurementTest.java
- services-turf/src/test/java/com/mapbox/turf/TurfMetaTest.java
- services-turf/src/test/java/com/mapbox/turf/TurfMiscTest.java
- services-turf/src/test/java/com/mapbox/turf/TurfTransformationTest.java
> removed dependency of Turf library on services-core

- CHANGELOG.md
Bringing https://github.com/mapbox/mapbox-java/pull/982 into the project
> fix wrong release dates for v4.5.0 and v4.4.0

- services-directions/src/main/java/com/mapbox/api/directions/v5/models/BannerComponents.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/BannerInstructions.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/BannerText.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/BannerInstructionsTest.java
Resolves #951 by adjusting the several annotations which @Guardiola31337 listed in #951.
@osana , I don't believe there are any other downstream changes that need to happen based on these annotation updates, but if so, please let me know.
> Fixing banner MAS models to match what actually comes from Directions API

- build.gradle
Mapbox java sdk  uses [AutoValue library](https://github.com/google/auto/blob/master/value/userguide/index.md) to generate boilerplate code for  value setters / getters and to generate `equals`, `hashCode` and `toString` methods.
It is a useful tool. However, it was reported that generated `.java` files end up in the library jars. This is undersirable. This PR excludes `.java` files from being added to the library jars.
closes #989
> Exclude *.java from being added to library jars

- CHANGELOG.md
One of the important items included in 4.6.0 release did not make it to the change log.
Adding it with this PR.
[Release notes](https://github.com/mapbox/mapbox-java/releases) were updated.
> missed one entry in the changelog

- services-isochrone/src/main/java/com/mapbox/api/isochrone/IsochroneCriteria.java
- services-isochrone/src/main/java/com/mapbox/api/isochrone/IsochroneService.java
- services-isochrone/src/main/java/com/mapbox/api/isochrone/MapboxIsochrone.java
Resolves #996 by adding a required `/mapbox/` slug to the Isochrone API service's Retrofit request URL. Based on my demo app refactoring work in https://github.com/mapbox/mapbox-android-demo/pull/1029, the #996 bug renders the wrapper unusable. 
The API's docs
Totally fine if this is the wrong way to fix the bug. Figured I'd open something to get the conversation started.
> Adding userAgent parameter to Isochrone request retrofit call URL

- services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/MapboxGeocoding.java
- services-geocoding/src/test/java/com/mapbox/api/geocoding/v5/MapboxGeocodingTest.java
This PR adds a missing overloaded method Geocoder#bbox that takes in a BoundingBox from the geojson package. 
Now MapboxGeocoding#bbox supports:
- `BoundingBox`
- `Point, Point`
- `double, double, double, double`
- `String`
closes #841
> added overloaded method bbox that takes in a BoundingBox

- services-geojson/src/main/java/com/mapbox/geojson/Feature.java
- services-geojson/src/test/java/com/mapbox/geojson/FeatureTest.java
This PR make `Feature.get*Property()` methods return null if there is no property with a passed in key. This is exactly what corresponding javadoc is stating.
This PR also has tests to varify all `get*Property()` methods in the Feature
closes #902
> Feature.get*Property should return null for non-existent property

- services-turf/src/main/java/com/mapbox/turf/TurfTransformation.java
Bringing in an outside [PR ](https://github.com/mapbox/mapbox-java/pull/1012) to run on CI.
Check if the list is empty before getting its items. Also, add an
annotation to indicate that steps parameter should be greater than 0.
> Fix possible IndexOutOfBoundsException exception

- services-geojson/src/main/java/com/google/gson/typeadapters/RuntimeTypeAdapterFactory.java
- services-geojson/src/main/java/com/mapbox/geojson/BaseCoordinatesTypeAdapter.java
- services-geojson/src/main/java/com/mapbox/geojson/BaseGeometryTypeAdapter.java
- services-geojson/src/main/java/com/mapbox/geojson/BoundingBox.java
- services-geojson/src/main/java/com/mapbox/geojson/CoordinateContainer.java
- services-geojson/src/main/java/com/mapbox/geojson/Feature.java
- services-geojson/src/main/java/com/mapbox/geojson/FeatureCollection.java
- services-geojson/src/main/java/com/mapbox/geojson/GeoJson.java
- services-geojson/src/main/java/com/mapbox/geojson/Geometry.java
- services-geojson/src/main/java/com/mapbox/geojson/GeometryAdapterFactory.java
- services-geojson/src/main/java/com/mapbox/geojson/GeometryCollection.java
- services-geojson/src/main/java/com/mapbox/geojson/LineString.java
- services-geojson/src/main/java/com/mapbox/geojson/ListOfDoublesCoordinatesTypeAdapter.java
- services-geojson/src/main/java/com/mapbox/geojson/ListOfListOfPointCoordinatesTypeAdapter.java
- services-geojson/src/main/java/com/mapbox/geojson/ListOfPointCoordinatesTypeAdapter.java
- services-geojson/src/main/java/com/mapbox/geojson/ListofListofListOfPointCoordinatesTypeAdapter.java
- services-geojson/src/main/java/com/mapbox/geojson/MultiLineString.java
- services-geojson/src/main/java/com/mapbox/geojson/MultiPoint.java
- services-geojson/src/main/java/com/mapbox/geojson/MultiPolygon.java
- services-geojson/src/main/java/com/mapbox/geojson/Point.java
- services-geojson/src/main/java/com/mapbox/geojson/PointAsCoordinatesTypeAdapter.java
- services-geojson/src/main/java/com/mapbox/geojson/Polygon.java
- services-geojson/src/main/java/com/mapbox/geojson/gson/BoundingBoxTypeAdapter.java
- services-geojson/src/main/java/com/mapbox/geojson/gson/GeoJsonAdapterFactory.java
- services-geojson/src/main/java/com/mapbox/geojson/gson/GeometryGeoJson.java
This PR adds `@Keep` annotation to model and gson related classes in  geojson library. This should simplify the integration of geojson library when proguard is enabled.
closes #980
> Added @Keep annotation to ease integration of geojson library

- services-turf/src/main/java/com/mapbox/turf/TurfMeta.java
- services-turf/src/test/java/com/mapbox/turf/TurfMetaTest.java
This pr adds methods for getting a `List<Point>` from a `Feature`, `FeatureCollection`, or `Geometry`. These parameters were missing from our Turf for Java library, but are part of https://turfjs.org/docs/#coordAll .
Having these methods will be incredibly helpful for adding a number of new Turf methods to our Turf for Java library. Also unblocks https://github.com/mapbox/mapbox-java/pull/1007.
> Adding coordAll() versions for Feature, FeatureCollection, and Geometry parameters

- services-turf/src/main/java/com/mapbox/turf/TurfMeta.java
This pr adds some missing `@NonNull` annotations to `coordAll()` method parameters.
> Adding missing `@NonNull` annotations to coordAll() parameters

- samples/src/main/java/com/mapbox/samples/BasicDirections.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/DirectionsResponseFactory.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/DirectionsService.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/WalkingOptions.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/WalkingOptionsAdapterFactory.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsJsonObject.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/WalkingOptionsTest.java
This is currently blocked until testing on staging is complete.
> Added walking options

- services-directions/src/main/java/com/mapbox/api/directions/v5/WalkingOptions.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/models/WalkingOptionsTest.java
- Fixes walking options serialization to match what the service expects / generates
Follow up from https://github.com/mapbox/mapbox-java/pull/991#discussion_r282666632
For when walking options will be included in the `RouteOptions` (for offline) we expect them to be nested as follows 👀 
```json
{
"baseUrl": "http://localhost:50257/",
"user": "mapbox",
"profile": "walking",
"coordinates": [
[1.0, 1.0],
[5.0, 5.0]
],
"alternatives": true,
"language": "en",
"continue_straight": false,
"geometries": "polyline6",
"overview": "simplified",
"access_token": "pk.XXX",
"uuid": "cjhk3ouqm1voa3vp51vsd738n",
"walkingOptions": {
"walking_speed": 1.0,
"walkway_bias": 0.6,
"alley_bias": 0.7
}
}
```
```json
"walkingOptions": {
"walking_speed": 1.0,
"walkway_bias": 0.6,
"alley_bias": 0.7
}
``` …
> Fix walking options serialization

- docs/turf-port.md
- services-turf/src/main/java/com/mapbox/turf/TurfMeasurement.java
- services-turf/src/test/java/com/mapbox/turf/TurfMeasurementTest.java
- services-turf/src/test/resources/turf-envelope/feature-collection.geojson
This PR adds support for https://turfjs.org/docs/#envelope. It also fixes up bbox implementation by allowing any GeoJson as parameter and add support for feature and feature collection conversions. bboxPolygon has also been updated to allow for double[] which is the actual representation of bbox in turf vs the BoundingBox from geojson.
> TurfMeasurement#envelope

- services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/models/CarmenFeature.java
- services-geojson/src/main/java/com/mapbox/geojson/GeoJson.java
- services-geojson/src/main/java/com/mapbox/geojson/GeometryCollection.java
- services-geojson/src/main/java/com/mapbox/geojson/LineString.java
- services-geojson/src/main/java/com/mapbox/geojson/MultiLineString.java
- services-geojson/src/main/java/com/mapbox/geojson/MultiPoint.java
- services-geojson/src/main/java/com/mapbox/geojson/MultiPolygon.java
- services-geojson/src/main/java/com/mapbox/geojson/Point.java
- services-geojson/src/main/java/com/mapbox/geojson/Polygon.java
This PR makes `GeoJson` extend `Serializable`. 
Feature and FeatureCollection are now Serializable.
This was suggested by @LukasPaczos at
https://github.com/mapbox/mapbox-java/pull/1025#discussion_r283379248
> Making GeoJson extend Serializable

- docs/turf-port.md
This pr removes the last updated line from [the list of ported Turf methods](https://github.com/mapbox/mapbox-java/blob/master/docs/turf-port.md). It was clear that I/we forget to update the line despite adding `x` to recently ported methods. If a reader wants to know the last time the document was updated, the reader can use Github history to do that.
> Removed the last updated line from ported Turf method list

- services-turf/README.md
https://github.com/mapbox/mapbox-java/blob/master/services-turf/README.md needed an updated link to https://docs.mapbox.com/android/java/overview/turf/#installation
> Adjusted link to Turf installation instructions

- docs/turf-port.md
- services-turf/src/main/java/com/mapbox/turf/TurfMeasurement.java
- services-turf/src/test/java/com/mapbox/turf/TurfMeasurementTest.java
Port of https://turfjs.org/docs/#square
> TurfMeasurement#square

- services-tilequery/src/main/java/com/mapbox/api/tilequery/MapboxTilequery.java
- services-tilequery/src/main/java/com/mapbox/api/tilequery/TilequeryService.java
Resolves https://github.com/mapbox/mapbox-java/issues/1021 by refactoring references of `mapIds` to `tileSetIds`
cc @1ec5
> Rename references of `mapIds` to `tileSetIds`

- services-tilequery/src/main/java/com/mapbox/api/tilequery/MapboxTilequery.java
- services-tilequery/src/main/java/com/mapbox/api/tilequery/TilequeryService.java
This reverts https://github.com/mapbox/mapbox-java/pull/1022 (commit 072b984700db9ceeb1c8af6424316b8ee71694cf) because #1022 is SEMVER MAJOR and we hadn't decided to do a SEMVER major release yet.
> Revert "Rename references of `mapIds` to `tileSetIds` (#1022)"

- services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/GeocodingService.java
- services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/MapboxGeocoding.java
- services-geocoding/src/test/java/com/mapbox/api/geocoding/v5/MapboxGeocodingTest.java
Resolves #1048 by adding fuzzyMatch support to MapboxGeocoding. 
https://docs.mapbox.com/api/search/#forward-geocoding
> Added fuzzyMatch support to MapboxGeocoding

- services-turf/src/main/java/com/mapbox/turf/TurfMeasurement.java
- services-turf/src/test/java/com/mapbox/turf/TurfMeasurementTest.java
Resolves https://github.com/mapbox/mapbox-java/issues/1042 by adjusting and adding TurfMeasurement#bboxPolygon() methods so that a `Feature` is returned instead of a `Polygon`. This pr also exposes properties and id parameters.
> Adjustments to TurfMeasurement#bboxPolygon() to return a Feature instead of Polygon

- services-turf/src/main/java/com/mapbox/turf/TurfMisc.java
- services-turf/src/test/java/com/mapbox/turf/TurfMiscTest.java
This pr resolves #1054 by adjusting `TurfMisc.nearestPointOnLine()` to use `TurfConstants.UNIT_KILOMETERS` by default. This pr also exposes a version of `TurfMisc.nearestPointOnLine()` which takes in a `@TurfConstants.TurfUnitCriteria` String so that a developer can pass in a preferred distance unit. 
cc @gwimmel , who requested this.
> Added new nearestPointOnLine default and custom distance unit

- services-geojson/src/main/java/com/mapbox/geojson/shifter/CoordinateShifterManager.java
- services-geojson/src/test/java/com/mapbox/geojson/shifter/ShifterTest.java
> Add an API to check if a custom shifter is set.

- README.md
This pr makes a small adjustment in the repo's README.  `compile` to `implementation`.
> README doc compile to implementation

- build.gradle
- circle.yml
- gradle/gradle-bintray.gradle
Follow up to https://github.com/mapbox/mapbox-java/pull/1064.
See the following binaries to validate these changes:
> mapbox-sdk-services-4.9.1-20190710.081438-5-javadoc.jar   10-Jul-2019 08:14  597.58 KB
mapbox-sdk-services-4.9.1-20190710.081438-5-sources.jar   10-Jul-2019 08:14  144.96 KB
mapbox-sdk-services-4.9.1-20190710.081438-5.jar           10-Jul-2019 08:14  402.67 KB
mapbox-sdk-services-4.9.1-20190710.081438-5.pom           10-Jul-2019 08:14  1.64 KB
https://oss.jfrog.org/artifactory/oss-snapshot-local/com/mapbox/mapboxsdk/mapbox-sdk-services/4.9.1-SNAPSHOT/
cc @gwimmel
> fixup bintray publish script, generate sources and javadoc jars

- CHANGELOG.md
- README.md
- gradle.properties
This pr makes changes as part of the `4.9.0-alpha.1` release of the Mapbox Java SDK.
> Changelog updates for 4.9.0-alpha.1 release

- services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/MapboxGeocoding.java
- services-turf/src/main/java/com/mapbox/turf/TurfConversion.java
I incorrectly advised @peng to use the `@since 4.10.0` annotation rather than `@since 4.9.0` in https://github.com/mapbox/mapbox-java/pull/1074 and https://github.com/mapbox/mapbox-java/pull/1075 . This pr fixes the `4.10.0` usage to `4.9.0`.
> Adjust @since 4.10.0 annotations to 4.9.0

- docs/turf-port.md
- services-turf/src/main/java/com/mapbox/turf/TurfConversion.java
- services-turf/src/test/java/com/mapbox/turf/TurfConversionTest.java
This pr ports the combine method to Turf for Java. This method takes a `FeatureCollection` of `Point`, `LineString`, or `Polygon` features and returns a `Geometry`. The returned `Geometry` can be used to create a `MultiPoint`, `MultiLineString`, or `MultiPolygon` feature.
http://turfjs.org/docs/#combine
https://github.com/Turfjs/turf/blob/master/packages/turf-combine/index.ts
`combine(FeatureCollection featureCollection)` is the new method added to the `TurfConversion` class.
> Adding combine turf method

- services-directions/src/main/java/com/mapbox/api/directions/v5/models/BannerText.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
Fix: `BannerText`, `RouteOptions` builders return nullable itself with in some cases
> BannerText, RouteOptions builders: removed nullable annotations

- services-turf/src/main/java/com/mapbox/turf/TurfConversion.java
This pr replaces `NotNull` and its import line with `NonNull`. This fixes a bug that has shown up downstream in many of Mapbox's own projects as well as our customers' work.
> Replaced NotNull with NonNull annotation in TurfConversion class

- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
Unable to hook up stetho to mapbox directions
https://github.com/facebook/stetho/blob/5cc93ec78908cdded19c5352a90635a33cf2fa7f/stetho-okhttp3/src/main/java/com/facebook/stetho/okhttp3/StethoInterceptor.java#L69-L71
> Add network interceptor to directions

- services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/GeocodingCriteria.java
- services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/GeocodingService.java
- services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/MapboxGeocoding.java
ref https://github.com/mapbox/android-docs/pull/1118
@langsmith, if you're good with these changes they can go out with the next release you do!
> Remove references to enterprise requirement from geocoding docs

- services-directions/src/main/java/com/mapbox/api/directions/v5/models/BannerComponents.java
From the discussion while adding junction views. It would be nice to have a type here. 
https://github.com/mapbox/mapbox-java/pull/1097#discussion_r364410214
> Add banner component type

- services-directions-models/src/main/java/com/mapbox/api/directions/v5/WalkingOptions.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/WalkingOptionsTest.java
Only `RouteOptions`  and `WalkingOptions` don't have `toBuilder()` method.
> Add toBuilder() method

- services-staticmap/src/main/java/com/mapbox/api/staticmap/v1/StaticMapCriteria.java
- services-staticmap/src/test/java/com/mapbox/api/staticmap/v1/MapboxStaticMapTest.java
Resolves https://github.com/mapbox/mapbox-java/issues/1106 by bumping the `StaticMapCriteria` class' constant style strings to new versions. They were all outdated by one version. 
cc @riastrad
> Bumped StaticMapCriteria constant style strings to new versions

- samples/src/main/java/com/mapbox/samples/BasicDirectionsRefresh.java
- services-core/src/main/java/com/mapbox/core/utils/TextUtils.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/utils/FormatUtils.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/utils/ParseUtils.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/utils/package-info.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/DirectionsResponseFactory.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
- services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java
- services-matching/src/main/java/com/mapbox/api/matching/v5/MatchingResponseFactory.java
- services-matching/src/test/java/com/mapbox/api/matching/v5/MapMatchingRouteOptionsTest.java
- services-matching/src/test/java/com/mapbox/api/matching/v5/MapboxMapMatchingTest.java
- services-matrix/src/main/java/com/mapbox/api/matrix/v1/MapboxMatrix.java
- services-optimization/src/main/java/com/mapbox/api/optimization/v1/MapboxOptimization.java
Curent PR also has changes from https://github.com/mapbox/mapbox-java/pull/1115
> RouteOptions and MapboxDirections refactoring

- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/utils/FormatUtils.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/utils/ParseUtils.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/DirectionsResponseFactory.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
- services-geojson/src/main/java/com/mapbox/geojson/BaseCoordinatesTypeAdapter.java
removed `bearing` validation logic from `MapboxDirections`
now both `RouteOptions` and `MapboxDirections` use `FormatUtils.formatBearings()` to build a valid string from a list of bearings
closes #1120
> Bearing formatting fix

- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/utils/ParseUtils.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
closes #1122 
Changed `RouteOptions` to store data in Strings (not in Lists). It had to be done to save semver.
So, if you pass a list of radiuses for example, it will be stored as a String.
If you want to get a list of radiuses, inner String will be converted to a returned list.
Removed any extra logic from String <-> List converting.
So, you you pass a list with null values, they won't be removed
`set radiusesList(listOf(1, 2, null, null))` -> `"1;2;;"`
get radiusesList() from `"1;2;;"` -> `[1, 2, null, null]`
Also changed parsing logic for `annotations`. They have to be separated with `comma`, not `semicolon`.
> RouteOptions parsing fixes

- README.md
This pr updates the link to the correct place to find SNAPSHOT versions
> Updated SNAPSHOT link in README

- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-matrix/src/main/java/com/mapbox/api/matrix/v1/MapboxMatrix.java
- services-matrix/src/test/java/com/mapbox/api/matrix/v1/MapboxMatrixTest.java
Resolves https://github.com/mapbox/mapbox-java/issues/1124 by adding support for Matrix API calls with a coordinate list size that's greater than 25. 
After approval from the Mapbox team, a Mapbox account can make Matrix API calls with a coordinate list that's larger than the default of 25. This pr unblocks users from using the Java SDK's `MapboxMatrix.builder()` to make those 26+ calls.
This pr introduces a `.coordinateListSizeLimit()` method, which takes an `Integer` parameter. The parameter represents the new max number of coordinates per call. If the number passed through is higher than what the Mapbox account is allowed (e.g. passing `.coordinateListSizeLimit(50)` when 25 is still the max limit for that Mapbox account/token), the backend API response will respond with an error …
> Adding flexibility to Matrix API builder to set custom max coordinate list size limit

- services-turf/src/main/java/com/mapbox/turf/TurfMeasurement.java
I'm looking to use some of these functions but want to use List<Point> directly.
> Refactor turf measurement functions

- CHANGELOG.md
- README.md
Addresses https://github.com/mapbox/mapbox-java/issues/1143
Link to release https://github.com/mapbox/mapbox-java/releases/tag/v5.2.0
> Release 5.2.0

- docs/turf-port.md
- services-turf/src/main/java/com/mapbox/turf/TurfMeasurement.java
- services-turf/src/test/java/com/mapbox/turf/TurfMeasurementTest.java
This pr ports http://turfjs.org/docs/#center (https://github.com/Turfjs/turf/blob/master/packages/turf-center/index.ts) to the Mapbox Java SDK. 
Having `TurfMeasurement.center()` inches us one step closer to porting http://turfjs.org/docs/#buffer. The center method is declared [here](https://github.com/Turfjs/turf/blob/master/packages/turf-buffer/index.js#L1) in the turf.js buffer file. Buffer porting is being tracked at https://github.com/mapbox/mapbox-java/issues/987.
> Porting TurfMeasurement.center

- services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/MapboxGeocoding.java
- services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/SingleElementSafeListTypeAdapter.java
- services-geocoding/src/test/java/com/mapbox/api/geocoding/v5/GeocodingTestUtils.java
- services-geocoding/src/test/java/com/mapbox/api/geocoding/v5/MapboxGeocodingTest.java
- services-geocoding/src/test/java/com/mapbox/api/geocoding/v5/SingleElementSafeListTypeAdapterTest.java
- services-geocoding/src/test/resources/geocoding_batch_single_object.json
Closes https://github.com/mapbox/mapbox-java/issues/1119
Geocoding search service response has a different format depending on the query type
- if a query contains `;`, the service returns an array of results, represented as JSON array `[{...}, {...}, ...]`
- otherwise, the server returns JSON object `{...}`
This PR adds flexible JSON parsing that can handle both cases.
> Correct handling of a single element batch geocoding response

- services-geojson/src/main/java/com/mapbox/geojson/Point.java
This PR removed the FloatRange annotations from Point.java. [The GeoJSON RFC](https://tools.ietf.org/html/rfc7946) doesn't enforce that longitude or latitude values should be ranged. While there are notes about representing geometries crossing the antimeridian and not expanding ranges when implementing spherical caps, the assumptions that longitude/latitdue values should be limited are not part of the spec.
This change is needed to unblock work downstream where we need to unproject/project points.
> [geojson] remove min/max latitude/longitude range annotations 

- gradle.properties
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/DirectionsRoute.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/LegStep.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteLeg.java
Added `durationTypical` field for road([DirectionsRoute](https://github.com/mapbox/mapbox-java/blob/master/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/DirectionsRoute.java)), road's leg([RouteLeg](https://github.com/mapbox/mapbox-java/blob/master/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteLeg.java)) and leg's step([LegStep](https://github.com/mapbox/mapbox-java/blob/master/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/LegStep.java)). It shows up duration of turn-by-turn navigation including delays(like a traffic jam)
VERSION_NAME updated `5.1.0-SNAPSHOT` -> `5.4.1-SNAPSHOT`
> DirectionRoute: added `durationTypical` for Route, Leg and Step; VERSION_NAME: updated to `5.4.1-SNAPSHOT`

- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/StepIntersection.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/StepIntersectionTest.java
Exposes already available `geometry_index` property of the step intersections.
> expose intersection's `geometry_index`

- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/Admin.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/MapboxStreetsV8.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RestStop.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteLeg.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/StepIntersection.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/TollCollection.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteLegTest.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/StepIntersectionTest.java
This PR exposes:
- `leg.admins` (An array of objects describing the administrative boundaries the route leg travels through)
- `intersections.admin_index` (The zero-based index into the admin list on the route leg for this intersection)
- `intersections.rest_stop` (An object containing information about passing rest stops along the route)
- `intersections.toll_collection` (An object containing information about a toll collection point along the route)
> Expose border crossings, rest stops and toll collection

- services-turf/src/test/java/com/mapbox/turf/TestUtils.java
Tests in this repository have never worked for me. I've relied on CircleCI to work correctly. Here is the error I get.
```
java.lang.NullPointerException: source
at java.util.Objects.requireNonNull(Objects.java:228)
at java.util.Scanner.init(Scanner.java:578)
at com.mapbox.core.TestUtils.loadJsonFixture(TestUtils.java:33)
..
```
I kind of like what this person says on the internet. "You don't need to mess with class loaders. In fact it's a bad habit to get into because class loader resources are not java.io.File objects when they are in a jar archive."
https://stackoverflow.com/questions/28673651/how-to-get-the-path-of-src-test-resources-directory-in-junit
After taking that approach, all these tests work locally. (ignore the ignored tests, not addressing that right now 😄 )
> Fix tests running locally

- services-turf/src/main/java/com/mapbox/turf/TurfTransformation.java
This pr duplicates @snkashis's work in https://github.com/mapbox/mapbox-java/pull/1178. CircleCI wouldn't run https://github.com/mapbox/mapbox-java/pull/1178 because @snkashis isn't a Mapboxer.
Thanks for your contributions @snkashis!
> Adjusting javadoc info about Turf circle methods

- CHANGELOG.md
Release 5.8.0-beta.2
Move `List<Incidents>` from `LegStep` to `RouteLeg` #1207
> Release 5.8.0-beta.2

- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/IntersectionLanes.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/IntersectionLanesTest.java
Closes https://github.com/mapbox/mapbox-java/issues/1195.
> expose `active` and `validIndications` lane information

- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/utils/ParseUtils.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/DirectionsService.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
The Directions API has added a new request parameter that allows routing from/to closed road segments (due to live-traffic closures). The draft documentation of this parameter is [here](https://github.com/mapbox/api-documentation/pull/1078/files) and this is live in production.
We need to support it.
> Snapping closures

- gradle/artifact-settings.gradle
Following up from here https://github.com/mapbox/mapbox-java/pull/1233
The snapshot I published wasn't loaded, reason is because it had a v on it. While I'm at it, fix the releases.
Old `v5.10.0-SNAPSHOT`
New `5.10.0-SNAPSHOT`
> Remove v from snapshots and releases

- .circleci/config.yml
Refactoring some to make the configuration follow some suggestions here https://circleci.com/docs/2.0/reusing-config/
In parallel, run builds, tests, and reports
Run builds tests reports, after success - create and publish a snapshot
Run builds tests reports, after success - create and publish a release
> Require jobs before release

- .circleci/config.yml
- cloudformation/ci.template
After a commit, both the snapshot and the default workflow are triggered. Move the snapshot workflow into default, to remove the duplication of work.
The release tag failed because it cannot check if existing releases are on s3. Add the s3:ListObject permission.
> Move snapshot to default workflow and add another fix to releases

- cloudformation/ci.template
More release failures.
```
> AWS S3 ls command failed with error code 255: 
An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```
Really need to follow the documentation 😅 
https://github.com/mapbox/mapbox-android-gradle-plugins/tree/main/sdk-registry
> Move list bucket cloudformation statement

- services-directions/src/main/java/com/mapbox/api/directions/v5/DirectionsResponseFactory.java
SnappingClosures options was not added to a response options. This PR fixes it
we should cover such cases with tests https://github.com/mapbox/mapbox-java/issues/1243
> Add snapping closures to a response options

- .circleci/config.yml
- Makefile
EDIT: we can't publish to api-downloads with CI yet. Changed this pull request to only simplify the commands
1. Add CHANGELOG.md and merge pull request
2. Copy changes and tag a new release to https://github.com/mapbox/mapbox-java/releases
3. `$ make sdk-registry-publish`
Following up to update documentation: https://github.com/mapbox/android-internal/issues/130
> Simplify release publishing

- services-directions-models/src/main/java/com/mapbox/api/directions/v5/DirectionsCriteria.java
Adding annotation closure constant to directions criteria.  This is related to issue #1249.
> Adding annotation closure constant to directions criteria.

- .circleci/config.yml
Temporarily disables codecov due to https://about.codecov.io/security-update/.
> temporarily disable codecov

- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/DirectionsResponse.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/DirectionsRoute.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
- services-directions-models/src/test/resources/route_options_v5.json
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
- services-directions/src/test/resources/route_options_v5.json
Ensures that access tokens are not serialized in order to avoid often unintentional leaks of the data when paired with other tools and utilities that serialize and store either the whole route response, route, or only the options. Unfortunately, due to the limitations of the code generation tools used we need to make the token field nullable until we find a better solution.
I also tried upgrading the https://github.com/rharter/auto-value-gson library that is used in this project to the latest version but it didn't seem to have the features needed to support a non-nullable property that is also not serializable and initialize it externally. We can cut a feature request, contribute, or think about a different solution in the future.
> Do not serialize access tokens

- CHANGELOG.md
- README.md
not sure if we should mention both
- Stopped serializing access tokens [#1267](https://github.com/mapbox/mapbox-java/pull/1267)
- Made the access token non-nullable in `RouteOptions` [#1270](https://github.com/mapbox/mapbox-java/pull/1270)
maybe a single [#1267] is enough.
> 6.0.0-alpha.1 changelog

- samples/src/main/java/com/mapbox/samples/BasicDirections.java
- samples/src/main/java/com/mapbox/samples/BasicDirectionsRefresh.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/DirectionsResponse.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/DirectionsRoute.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/DirectionsResponseTest.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/DirectionsRouteTest.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
- services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java
- services-directions/src/test/java/com/mapbox/api/directions/v5/MapboxDirectionsTest.java
- services-matching/src/main/java/com/mapbox/api/matching/v5/MatchingResponseFactory.java
- services-matching/src/test/java/com/mapbox/api/matching/v5/MapMatchingRouteOptionsTest.java
Closes https://github.com/mapbox/mapbox-java/issues/1275. Moves the `accessToken` parameter from `RouteOptions` to `MapboxDirections`.
> Removed access token from RouteOptions

- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/Incident.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/IncidentTest.java
Fixes #1287 
**Before**
```
2021-08-30 10:57:04.438 30289-30289/com.mapbox.navigation.examples D/abhishek_testing: incident: Incident{id=15206143733423687, type=lane_restriction, closed=null, congestion=Congestion{value=101}, description=Lilienthalallee: Bauarbeiten zwischen Heidemannstrasse und Frankfurter Ring, longDescription=Vorübergehende Ampelregelung und ein alternativer Linienverkehr wegen Bauarbeiten auf der Lilienthalallee in beiden Richtungen zwischen Heidemannstrasse und Frankfurter Ring., impact=low, subType=CONSTRUCTION, subTypeDescription=null, alertcCodes=[742, 708], geometryIndexStart=4, geometryIndexEnd=44, creationTime=2021-08-30T17:40:33Z, startTime=2020-09-14T05:30:00Z, endTime=2021-10-01T13:00:00Z}
```
**After**
```
2021-08-30 11:09:46.077 …
```
> add missing properties to Incident object

- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/BannerComponents.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/BannerComponentTest.java
Adding `active_direction` to `BannerComponents` which was added in directions response based on valhalla routing engine. This is required for refactoring turn lane.
> add active direction to banner component

- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
closes https://github.com/mapbox/mapbox-java/issues/1313
can't use`java.net.URL` case it doesn't have handy methods to build URL, so use okhttp `HttpUrl`
also some symbols were encoded:
; -> %3B
, -> %2C
it shouldn't be an issue, right?
> Refactor RouteOptions.toUrl

- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
Follow up to https://github.com/mapbox/mapbox-java/pull/1314. Added encoding for parameters transformed with `RouteOptions#toUrl()`.
> added encoding for RouteOptions.toUrl

- .github/CODEOWNERS
@colleenmcginnis and @danswick will be assigned to every PR in publisher-production automatically
> Added code owners for publisher-production

- .circleci/config.yml
- Makefile
- scripts/publish_api_docs_android.sh
The script automatically cuts a PR with generated documentation to the `publisher-production` branch. See #1321 as an example. 
This time I did a great job testing it.
I launched script locally without changes and got #1321 
Then I launched the script from the circleci with hardcoded values and got  #1324
> Generate docs automatically

- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/DirectionsResponse.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/DirectionsResponseTest.java
- services-directions-models/src/test/resources/directions_v5_multiple_routes_with_options.json
Fixes a regression from https://github.com/mapbox/mapbox-java/pull/1328 and makes sure that `RouteOptions` are correctly deserialized when provided within the serialized response.
> fixes an issue where RouteOptions weren't deserialized from JSON DirectionsResponse

- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
Makes sure that no forbidden characters are found in the encoded URL. With the old approach, all characters were escaped correctly but UTF-8 characters were not encoded.
> when encoding RouteOptions to URL use UTF-8

- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/ShieldSprite.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/ShieldSpriteAttribute.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/ShieldSprites.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/ShieldSvg.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/ShieldSpritesTest.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/ShieldSvgTest.java
- services-directions-models/src/test/resources/styles_shield_sprites.json
- services-directions-models/src/test/resources/styles_svg.json
Fixes https://github.com/mapbox/mapbox-java/issues/1316
Opening this as a `Draft` as there are still some open questions that need to be addressed downstream in the BE:
- As a response we're getting
```json
{
"turning-circle-outline": {
"width": 138,
"height": 138,
"x": 0,
"y": 0,
"pixelRatio": 1,
"visible": true
},
"turning-circle": {
"width": 126,
"height": 126,
"x": 138,
"y": 0,
"pixelRatio": 1,
"visible": true
},
"us-interstate-truck-2": {
"width": 60,
"height": 120,
"x": 0,
"y": 138,
"pixelRatio": 1,
"placeholder": [0, 17, 20, 23],
"visible": true
}
}
```
Can we get instead 
```json
{
"sprites": [{
"sprite_name": "turning-circle-outline",
"sprite_attributes": {
"width": 138,
"height": 138,
"x": 0,
"y": 0,
"pixel_ratio": 1,
"visible": true
}
}, {
"sprite_name": "turning-circle", …
```
> Add styles API models

- CODEOWNERS.md
- services-geocoding/README.md
[Search SDK for Android](https://docs.mapbox.com/android/search/guides/) now is the recommended way to access Geocoding API on Android platform.  
To promote Search SDK usage this PR:
1) Adds `Geocoder` deprecation note;
2) Assigns `services-geocoding` ownership to @mapbox/search-sdk-android  team
> Promote `Search SDK` as a replacement of `Geocoder`

- services-turf/src/main/java/com/mapbox/turf/TurfMisc.java
- services-turf/src/test/java/com/mapbox/turf/TurfMiscTest.java
Implement line intersect which is equivalent to [turf.lineIntersect](https://turfjs.org/docs/#lineIntersect) with a primitive manner.
> Primitive implementation of line intersect

- .circleci/config.yml
Latest docker image swapped Java version used from 8 to 11 which broke this project's compilation. This PR downgrades the image version to the latest based on Java 8.
We can iterate from here and migrate `mapbox-java` to be compatible with Java 11 but proposing this quick fix to unblock snapshot releases needed for downstream project.
> downgrade docker image to use Java 8

- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/DirectionsWaypoint.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/DirectionsWaypointTest.java
Updated nullability annotations and exposed optional `distance` property. Refs https://docs.mapbox.com/api/navigation/directions/#waypoint-object.
> Updated DirectionsWaypoint object

- CHANGELOG.md
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/DirectionsCriteria.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/Exclude.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/ExcludeTest.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsExcludeTest.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
- services-directions-models/src/test/resources/route_options_v5.json
Direction API provides a new feature "exclude waypoint". To exclude a coordinate form your route add it to the list of `exclude` like `point(lon lat)`. For example if you want to exclude motorways and coordinate `1.0 1.0` use following exclude param: `exclude=motorway,point(1.0%201.0)`
You're reviewing a second iteration of the exclude waypoints implementation. First iteration is #1361.
> Exclude waypoints from routing 

- CHANGELOG.md
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
Ensures that port number is deserialized from URL.
> handle custom port number in RouteOptions#fromUrl

- services-matching/src/main/java/com/mapbox/api/matching/v5/MapMatchingService.java
- services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java
- services-matching/src/main/java/com/mapbox/api/matching/v5/models/MapMatchingMatching.java
- services-matching/src/test/java/com/mapbox/api/matching/v5/MapboxMapMatchingTest.java
closes https://github.com/mapbox/mapbox-java/issues/1304
> MapMatching: added ignore param

- CHANGELOG.md
- README.md
- Added `Incident.affectedRoadNames`. [#1457](https://github.com/mapbox/mapbox-java/pull/1457)
- Added `StepIntersections.trafficSignal`,`StepIntersections.stopSign` and `StepIntersections.yieldSign`. [#1464](https://github.com/mapbox/mapbox-java/pull/1464)
- Fixed an issue where the `MapMatchingMathcing#routeIndex` wasn't correctly assigned. [#1463](https://github.com/mapbox/mapbox-java/pull/1463)
> 6.7.0-beta.1 changelog

- config/checkstyle/checkstyle.xml
Add `SuppressWarnings` annotation that would allow for adding type safe bindings without documentation.
Usage of annotations:
For suppressing `method` documentation
```
@SuppressWarnings("checkstyle:javadocmethod")
@NonNull
public abstract Builder guideMap(@Nullable String guideMap);
```
For suppressing `variable` documentation
```
@SuppressWarnings("checkstyle:javadocvariable")
public static final String SAPAGUIDEMAP = "sapaguidemap";
```
cc @mapbox/navigation-android
> Add `SuppressWarnings` annotation that would allow for adding type safe bindings without documentation.

- CHANGELOG.md
- README.md
- Replaced `TurfSimplify#simplify` with `TurfTransformation#simplify`. [#1496](https://github.com/mapbox/mapbox-java/pull/1496)
- Deprecated `PolylineUtils#simplify` in favour of `TurfTransformation#simplify`. [#1496](https://github.com/mapbox/mapbox-java/pull/1496)
> 6.8.0 changelog

- services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/GeocodingService.java
- services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/MapboxGeocoding.java
- services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/models/CarmenContext.java
- services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/models/CarmenFeature.java
- services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/models/RoutablePoint.java
- services-geocoding/src/main/java/com/mapbox/api/geocoding/v5/models/RoutablePoints.java
- services-geocoding/src/test/java/com/mapbox/api/geocoding/v5/MapboxGeocodingTest.java
- services-geocoding/src/test/java/com/mapbox/api/geocoding/v5/models/CarmenContextTest.java
- services-geocoding/src/test/java/com/mapbox/api/geocoding/v5/models/CarmenFeatureTest.java
- services-geocoding/src/test/resources/forward_feature_valid.json
- services-geocoding/src/test/resources/geocoding.json
Add [routable points](https://docs.mapbox.com/api/search/geocoding/) support for `services-geocoding`
> Routable points support for services-geocoding

- gradle/dependencies.gradle
Responds to https://nvd.nist.gov/vuln/detail/CVE-2022-25647 by using a patched-up version.
> update GSON to v2.8.9

- CHANGELOG.md
- services-core/src/test/java/com/mapbox/core/TestUtils.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/DirectionsResponse.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/DirectionsResponseTest.java
I want to deserialise direction response from `ByteBuffer` that is kept in native memory. See POC: https://github.com/mapbox/mapbox-java/pull/1526 and NAVAND-1037 for more details.
I decided to introduce a general purpose interface that accepts reader instead of byte buffer, while the transformation of byte buffer to reader will be done on the Navigation SDK side.
> NAVAND-1037 support streaming serialisation

- services-matching/src/main/java/com/mapbox/api/matching/v5/MapboxMapMatching.java
- services-matrix/src/main/java/com/mapbox/api/matrix/v1/MapboxMatrix.java
We get a complain from customer that matrix request stoped working after some time until device is rebooted. It turned out that they were reusing builder instance for different requests.
> Clarify documentation to avoid confusion 

- services-geojson/src/main/java/com/mapbox/geojson/BaseCoordinatesTypeAdapter.java
- services-geojson/src/main/java/com/mapbox/geojson/gson/BoundingBoxTypeAdapter.java
The issue corresponds to [NAVAND-2844](https://mapbox.atlassian.net/browse/NAVAND-2844) jura ticket. 
Reduces array default size in GSON adapters.
[NAVAND-2844]: https://mapbox.atlassian.net/browse/NAVAND-2844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NAVAND-2844] Improve array creation while parsing

- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/IntersectionLanes.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/IntersectionLanesTypeAdapter.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/StepManeuver.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/StepManeuverTypeAdapter.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/utils/ParseUtils.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/IntersectionLanesTest.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/StepManeuverTest.java
https://mapbox.atlassian.net/browse/NAVAND-3254
In the directions response format, there are string elements that can have a limited number of values but frequently occur in the JSON response. Some of them are: `IntersectionLanes.indications()`, `IntersectionLanes.validIndication()`, `StepManeuver.type()`, and `StepManeuver.modifier()`. The GSON parser does not support string interning, which leads to new string allocations every time. Consequently, the parsed route object contains many duplicate strings. In this PR, we introduce custom TypeAdapters that intern selected strings to save memory.
Some analysis for `IntersectionLanes` objects:
- Long route from Minsk to Oslo, through Munich, Stuttgart, and Paris (4.5K km)
- 7561 indications, 4773 valid indications, only 6 unique strings.
- …
> Optimize Memory Usage by Interning Frequently Occurring Strings in JSON

- CHANGELOG.md
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/PaymentMethods.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/DirectionsRouteTest.java
- services-directions-models/src/test/resources/directions_v5_with_toll_costs.json
Added `PaymentMethods#etc2` payment method.
> PaymentMethods.etc2

- CHANGELOG.md
- gradle/dependencies.gradle
Bumped okhttp to version 4.10.0.
Common was bumped last year. https://github.com/mapbox/mapbox-sdk-common/pull/3870
> Bumped okhttp to version 4.10.0.

- CHANGELOG.md
- services-isochrone/src/main/java/com/mapbox/api/isochrone/IsochroneCriteria.java
- services-isochrone/src/main/java/com/mapbox/api/isochrone/IsochroneService.java
- services-isochrone/src/main/java/com/mapbox/api/isochrone/MapboxIsochrone.java
- services-isochrone/src/test/java/com/mapbox/api/isochrone/MapboxIsochroneTest.java
Added updates to Isochrone API to support new features like driving-traffic profile, contours_meters,  road/route exclusions and departure date/time.
> Updates to Isochrone API

- CHANGELOG.md
- services-isochrone/src/main/java/com/mapbox/api/isochrone/MapboxIsochrone.java
- services-isochrone/src/test/java/com/mapbox/api/isochrone/MapboxIsochroneTest.java
The recent addition of contours_meters for the Isochrone API resulted in a malformed URL. This is a fix for that regression.
> Fix for malformed URL when using contours minutes/meters.

- CHANGELOG.md
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/DirectionsCriteria.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java
- services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/StepIntersection.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/DirectionsRouteTest.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java
- services-directions-models/src/test/java/com/mapbox/api/directions/v5/models/StepIntersectionTest.java
- services-directions-models/src/test/resources/directions_v5_with_toll_costs_and_lanes.json
- services-directions-models/src/test/resources/route_options_v5.json
Added support for:
- `StepIntersection#formOfWay`,
- `StepIntersection#geometries`
- `StepIntersection#access`
- `StepIntersection#elevated`
- `StepIntersection#bridge`
Also added a new voice unit value: `DirectionsCriteria#BRITISH_IMPERIAL`.
> Support for new route properties; Add BRITISH_IMPERIAL voice unit
